/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms.admin;

import data.Category;
import data.ClientConnection;
import data.ClientHelper;
import data.Platforms;
import data.Videogame;
import forms.Principal;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author CARLA LLENAS
 */
public class AltaVideojuegos extends javax.swing.JFrame {
    /**
     * constructor de la classe
     */
    public AltaVideojuegos() {
        initComponents();
        String[] Plat = new String[ClientHelper.listPlataformas.size()];
        int[] i = {0};
        ClientHelper.listPlataformas.forEach(p -> {
            Plat[i[0]] = p.getName();
            i[0]++;
        });

        String[] Cat = new String[ClientHelper.listCategory.size()];
        i[0] = 0;
        ClientHelper.listCategory.forEach(c -> {
            Cat[i[0]] = c.getCategory();
            i[0]++;
        });
        

        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelAltaVideojuegos = new javax.swing.JPanel();
        txtDate = new javax.swing.JTextField();
        btnAlta = new javax.swing.JButton();
        labelName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        labelDeveloper = new javax.swing.JLabel();
        txtDeveloper = new javax.swing.JTextField();
        labelDescrip = new javax.swing.JLabel();
        txtDescrip = new javax.swing.JTextField();
        labelReleaseDate = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        labelImage = new javax.swing.JLabel();
        labelPublisher = new javax.swing.JLabel();
        txtPublisher = new javax.swing.JTextField();
        txtImg = new javax.swing.JTextField();
        btnAtras = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnChoose = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelAltaVideojuegos.setBackground(new java.awt.Color(204, 255, 255));
        PanelAltaVideojuegos.setForeground(new java.awt.Color(0, 0, 0));
        PanelAltaVideojuegos.setLayout(null);

        txtDate.setToolTipText("yyyy-mm-dd");
        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });
        PanelAltaVideojuegos.add(txtDate);
        txtDate.setBounds(270, 281, 282, 32);

        btnAlta.setText("ALTA");
        btnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaActionPerformed(evt);
            }
        });
        PanelAltaVideojuegos.add(btnAlta);
        btnAlta.setBounds(430, 423, 122, 53);

        labelName.setForeground(new java.awt.Color(255, 255, 255));
        labelName.setText("Nombre del Videojuego");
        PanelAltaVideojuegos.add(labelName);
        labelName.setBounds(79, 96, 131, 16);
        PanelAltaVideojuegos.add(txtName);
        txtName.setBounds(270, 88, 282, 32);

        labelDeveloper.setForeground(new java.awt.Color(255, 255, 255));
        labelDeveloper.setText("Desarrollador");
        PanelAltaVideojuegos.add(labelDeveloper);
        labelDeveloper.setBounds(79, 159, 78, 16);

        txtDeveloper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeveloperActionPerformed(evt);
            }
        });
        PanelAltaVideojuegos.add(txtDeveloper);
        txtDeveloper.setBounds(270, 151, 282, 32);

        labelDescrip.setForeground(new java.awt.Color(255, 255, 255));
        labelDescrip.setText("Descripcion");
        PanelAltaVideojuegos.add(labelDescrip);
        labelDescrip.setBounds(79, 223, 68, 16);
        PanelAltaVideojuegos.add(txtDescrip);
        txtDescrip.setBounds(270, 215, 282, 32);

        labelReleaseDate.setForeground(new java.awt.Color(255, 255, 255));
        labelReleaseDate.setText("Fecha de lanzamiento");
        PanelAltaVideojuegos.add(labelReleaseDate);
        labelReleaseDate.setBounds(79, 297, 123, 16);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ALTA DE VIDEJUEGOS");
        PanelAltaVideojuegos.add(jLabel1);
        jLabel1.setBounds(422, 26, 174, 25);

        labelImage.setForeground(new java.awt.Color(255, 255, 255));
        labelImage.setText("Imagen");
        PanelAltaVideojuegos.add(labelImage);
        labelImage.setBounds(621, 267, 42, 16);

        labelPublisher.setForeground(new java.awt.Color(255, 255, 255));
        labelPublisher.setText("Publisher");
        PanelAltaVideojuegos.add(labelPublisher);
        labelPublisher.setBounds(79, 366, 54, 16);
        PanelAltaVideojuegos.add(txtPublisher);
        txtPublisher.setBounds(270, 350, 282, 32);
        PanelAltaVideojuegos.add(txtImg);
        txtImg.setBounds(593, 325, 375, 34);

        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        PanelAltaVideojuegos.add(btnAtras);
        btnAtras.setBounds(42, 444, 80, 32);
        PanelAltaVideojuegos.add(jSeparator1);
        jSeparator1.setBounds(53, 60, 927, 10);

        btnChoose.setText("Cargar Imagen");
        btnChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseActionPerformed(evt);
            }
        });
        PanelAltaVideojuegos.add(btnChoose);
        btnChoose.setBounds(698, 259, 225, 32);

        fondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\CARLA LLENAS\\OneDrive\\Documentos\\NetBeansProjects\\LudoxCliente\\src\\main\\images\\fondoMenuAdmin.jpg")); // NOI18N
        PanelAltaVideojuegos.add(fondo);
        fondo.setBounds(0, 0, 990, 490);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelAltaVideojuegos, javax.swing.GroupLayout.PREFERRED_SIZE, 986, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelAltaVideojuegos, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * botó que fa l'alta de videojocs a la base de dades
     */
    private void txtDeveloperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeveloperActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeveloperActionPerformed

    /**
     * metode que comprova que cap camp sigui null i fa l'alta d'un videojoc nou
     */
    private void btnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaActionPerformed
        // TODO add your handling code here:
        byte ok;

        if (!txtName.getText().trim().equals("")
                && !txtDeveloper.getText().trim().equals("")
                && !txtDescrip.getText().trim().equals("")
                && !txtPublisher.getText().trim().equals("")
                && !txtDate.getText().trim().equals("")
                && !txtImg.getText().trim().equals("")) {

            List<Platforms> listPlatforms = new ArrayList<>();
            List<Category> listCategory = new ArrayList<>();

            Videogame vg = new Videogame(
                    txtDescrip.getText(),
                    txtDeveloper.getText(),
                    txtName.getText(),
                    txtPublisher.getText(),
                    ConvertStringToDate(txtDate.getText()),
                    getImageAsBytes(txtImg.getText()));

            vg.setPlatforms(listPlatforms);
            vg.setCategories(listCategory);

            ok = sendVideogame(vg);

            switch (ok) {
                case 0:
                    System.out.println("Videjuego registrado");
                    JOptionPane.showMessageDialog(this, "Videojuego registrado correctamente");
                    break;
                case 1:
                    System.out.println("videojuego ya existe");
                    JOptionPane.showMessageDialog(this, "Este videojuego ya existe");
                    break;
                default:
                    System.out.println("error");
                    break;
            }
        }
    }//GEN-LAST:event_btnAltaActionPerformed

    /**
     * metode que converteix una dada string a tipus Date
     *
     * @param stringDate
     * @return date
     */
    public Date ConvertStringToDate(String stringDate) {
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy/MM/dd");
        Date date = new Date();

        try {
            date = formatter.parse(stringDate);
        } catch (ParseException ex) {
            Logger.getLogger(AltaVideojuegos.class.getName()).log(Level.SEVERE, null, ex);
        }
        return date;
    }

    /**
     * metode que transforma la imatge en bytes per poder enviarla al sevidor
     *
     * @param path
     * @return img
     */
    private byte[] getImageAsBytes(String path) {
        try {
            BufferedImage b = null;
            byte[] img;
            if (path != null && !path.trim().isEmpty()) {
                b = ImageIO.read(new File(path));
                ByteArrayOutputStream bos = new ByteArrayOutputStream();
                ImageIO.write(b, "png", bos);
                img = bos.toByteArray();
                return img;
            } else {
                return null;
            }
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    /**
     * metode que envia al servidor la petició de crear un videojoc
     *
     * @param v
     * @return valor byte del servidor
     */
    public byte sendVideogame(Videogame v) {
        try {
            ClientConnection.getDos().writeByte(6);
            ClientConnection.getOos().writeObject(v);
            return ClientConnection.getDis().readByte();

        } catch (IOException ex) {
            Logger.getLogger(Videogame.class.getName()).log(Level.SEVERE, null, ex);
            return 100;
        }
    }
    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed

    }//GEN-LAST:event_txtDateActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        this.dispose();
          
    }//GEN-LAST:event_btnAtrasActionPerformed

    /**
     * botó per carregar una imatge dels arxius.
     */
    private void btnChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseActionPerformed
        // TODO add your handling code here:
        String ruta = "";
        JFileChooser jFileChooser = new JFileChooser();
        FileNameExtensionFilter filtrado = new FileNameExtensionFilter("JPG, PNG", "jpg", "png");
        jFileChooser.setFileFilter(filtrado);

        int response = jFileChooser.showOpenDialog(this);
        if (response == JFileChooser.APPROVE_OPTION) {
            ruta = jFileChooser.getSelectedFile().getPath();
            txtImg.setText(ruta);
        }
    }//GEN-LAST:event_btnChooseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelAltaVideojuegos;
    private javax.swing.JButton btnAlta;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnChoose;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelDescrip;
    private javax.swing.JLabel labelDeveloper;
    private javax.swing.JLabel labelImage;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelPublisher;
    private javax.swing.JLabel labelReleaseDate;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtDescrip;
    private javax.swing.JTextField txtDeveloper;
    private javax.swing.JTextField txtImg;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPublisher;
    // End of variables declaration//GEN-END:variables
}
