/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms.admin;

import data.ClientConnection;
import data.User;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author CARLA LLENAS
 */
public class ControlUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form ControlUsuarios
     */
    public ControlUsuarios() {
        initComponents();
        try {
            Update();
        } catch (IOException ex) {
            Logger.getLogger(ControlUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ControlUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUsuarios = new javax.swing.JPanel();
        UsersList = new javax.swing.JScrollPane();
        UList = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelUsuarios.setBackground(new java.awt.Color(204, 204, 0));
        panelUsuarios.setLayout(null);

        UList.setBackground(new java.awt.Color(153, 153, 153));
        UList.setForeground(new java.awt.Color(255, 255, 255));
        UList.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                UListAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        UsersList.setViewportView(UList);

        panelUsuarios.add(UsersList);
        UsersList.setBounds(38, 89, 582, 481);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ADMINISTRAR USUARIOS");
        panelUsuarios.add(jLabel6);
        jLabel6.setBounds(300, 30, 220, 25);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        panelUsuarios.add(btnUpdate);
        btnUpdate.setBounds(670, 410, 90, 24);

        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        panelUsuarios.add(btnAtras);
        btnAtras.setBounds(670, 540, 100, 24);

        btnEliminar.setBackground(new java.awt.Color(255, 51, 51));
        btnEliminar.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminar.setText("Eliminar Usuario");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        panelUsuarios.add(btnEliminar);
        btnEliminar.setBounds(660, 120, 140, 24);

        fondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\CARLA LLENAS\\OneDrive\\Documentos\\NetBeansProjects\\LudoxCliente\\src\\main\\images\\fondoMenuAdmin.jpg")); // NOI18N
        panelUsuarios.add(fondo);
        fondo.setBounds(-2, 0, 820, 593);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 818, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UListAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_UListAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_UListAncestorAdded

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed

        // TODO add your handling code here:
        try {
            Update();
        } catch (IOException ex) {
            Logger.getLogger(ControlUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ControlUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        removeUser(false);
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * metode per actualitzar la llista d'usuaris
     */
    public void Update() throws IOException, ClassNotFoundException {
        ClientConnection.getDos().writeByte(11);
        List<User> usersList;
        usersList = (List<User>) ClientConnection.getOis().readObject();
        DefaultListModel<String> model = new DefaultListModel<>();

        UList.setModel(model);
        String[] usersNames;
        usersNames = usersList.stream().filter(u->!u.isIsAdmin()).map(v -> v.getUsername()).toArray(size -> new String[size]);

        for (int i = 0; i < usersNames.length; i++) {
            model.addElement(usersNames[i]);
        }
    }

    /**
     * metode per eliminar usuaris
     */
    public void removeUser(boolean enabled) {
        System.out.println(UList.getSelectedValue());
        try {
            ClientConnection.getDos().writeByte(12);
            ClientConnection.getDos().writeUTF(UList.getSelectedValue());
            ClientConnection.getDos().writeBoolean(enabled);
        } catch (IOException ex) {
            Logger.getLogger(ControlUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> UList;
    private javax.swing.JScrollPane UsersList;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel panelUsuarios;
    // End of variables declaration//GEN-END:variables
}
