/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms.admin;

import forms.Principal;

/**
 *
 * @author CARLA LLENAS
 */
public class Permisos extends javax.swing.JFrame {

    Principal prin;

    /**
     * Creates new form Permisos
     */
    public Permisos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPermisos = new javax.swing.JPanel();
        UsersList = new javax.swing.JScrollPane();
        GamesList = new javax.swing.JList<>();
        btnConvertToAdmin = new javax.swing.JButton();
        btnNoAdmin = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        radioBtnIsAdmin = new javax.swing.JRadioButton();
        btnUpdate = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPermisos.setBackground(new java.awt.Color(204, 204, 0));
        panelPermisos.setLayout(null);

        GamesList.setBackground(new java.awt.Color(153, 153, 153));
        GamesList.setForeground(new java.awt.Color(255, 255, 255));
        GamesList.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                GamesListAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        UsersList.setViewportView(GamesList);

        panelPermisos.add(UsersList);
        UsersList.setBounds(38, 89, 582, 481);

        btnConvertToAdmin.setText("Convertir Administrador");
        panelPermisos.add(btnConvertToAdmin);
        btnConvertToAdmin.setBounds(630, 160, 170, 32);

        btnNoAdmin.setText("Quitar Administrador");
        panelPermisos.add(btnNoAdmin);
        btnNoAdmin.setBounds(630, 250, 170, 32);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ADMINISTRAR PERMISOS DE USUARIO");
        panelPermisos.add(jLabel6);
        jLabel6.setBounds(250, 30, 330, 25);

        radioBtnIsAdmin.setText("isAdmin");
        panelPermisos.add(radioBtnIsAdmin);
        radioBtnIsAdmin.setBounds(641, 360, 130, 28);

        btnUpdate.setText("Update");
        panelPermisos.add(btnUpdate);
        btnUpdate.setBounds(660, 410, 90, 32);

        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        panelPermisos.add(btnAtras);
        btnAtras.setBounds(670, 540, 100, 32);

        fondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\CARLA LLENAS\\OneDrive\\Documentos\\NetBeansProjects\\LudoxCliente\\src\\main\\images\\fondoMenuAdmin.jpg")); // NOI18N
        panelPermisos.add(fondo);
        fondo.setBounds(-2, 0, 820, 593);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPermisos, javax.swing.GroupLayout.PREFERRED_SIZE, 818, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPermisos, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GamesListAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_GamesListAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_GamesListAncestorAdded

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        prin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Permisos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Permisos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Permisos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Permisos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Permisos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> GamesList;
    private javax.swing.JScrollPane UsersList;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnConvertToAdmin;
    private javax.swing.JButton btnNoAdmin;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel panelPermisos;
    private javax.swing.JRadioButton radioBtnIsAdmin;
    // End of variables declaration//GEN-END:variables
}
