/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms.admin;

import data.ClientConnection;
import data.User;
import forms.Principal;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author CARLA LLENAS
 */
public class Permisos extends javax.swing.JFrame {

    /**
     * Creates new form Permisos
     */
    public Permisos() {
        initComponents();
        try {
            Update();
        } catch (IOException ex) {
            Logger.getLogger(Permisos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Permisos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPermisos = new javax.swing.JPanel();
        UsersList = new javax.swing.JScrollPane();
        UList = new javax.swing.JList<>();
        btnConvertToAdmin = new javax.swing.JButton();
        btnNoAdmin = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        radioBtnIsAdmin = new javax.swing.JRadioButton();
        btnUpdate = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPermisos.setBackground(new java.awt.Color(204, 204, 0));
        panelPermisos.setLayout(null);

        UList.setBackground(new java.awt.Color(153, 153, 153));
        UList.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        UList.setForeground(new java.awt.Color(0, 0, 0));
        UList.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                UListAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        UsersList.setViewportView(UList);

        panelPermisos.add(UsersList);
        UsersList.setBounds(38, 89, 582, 481);

        btnConvertToAdmin.setText("Convertir Administrador");
        btnConvertToAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertToAdminActionPerformed(evt);
            }
        });
        panelPermisos.add(btnConvertToAdmin);
        btnConvertToAdmin.setBounds(630, 160, 170, 24);

        btnNoAdmin.setText("Quitar Administrador");
        btnNoAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoAdminActionPerformed(evt);
            }
        });
        panelPermisos.add(btnNoAdmin);
        btnNoAdmin.setBounds(630, 250, 170, 24);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ADMINISTRAR PERMISOS DE USUARIO");
        panelPermisos.add(jLabel6);
        jLabel6.setBounds(250, 30, 330, 25);

        radioBtnIsAdmin.setText("isAdmin");
        panelPermisos.add(radioBtnIsAdmin);
        radioBtnIsAdmin.setBounds(641, 360, 130, 28);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        panelPermisos.add(btnUpdate);
        btnUpdate.setBounds(660, 410, 90, 24);

        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        panelPermisos.add(btnAtras);
        btnAtras.setBounds(670, 540, 100, 24);

        fondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\CARLA LLENAS\\OneDrive\\Documentos\\NetBeansProjects\\LudoxCliente\\src\\main\\images\\fondoMenuAdmin.jpg")); // NOI18N
        panelPermisos.add(fondo);
        fondo.setBounds(-2, 0, 820, 593);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPermisos, javax.swing.GroupLayout.PREFERRED_SIZE, 818, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPermisos, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UListAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_UListAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_UListAncestorAdded

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        this.dispose();       
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnConvertToAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertToAdminActionPerformed
        // TODO add your handling code here:
        changeAdmin(true);
    }//GEN-LAST:event_btnConvertToAdminActionPerformed

    private void btnNoAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoAdminActionPerformed
        // TODO add your handling code here:
        changeAdmin(false);
    }//GEN-LAST:event_btnNoAdminActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            // TODO add your handling code here:
            Update();
        } catch (IOException ex) {
            Logger.getLogger(Permisos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Permisos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * metode per actualitzar la llista d'usuaris 
     */
    public void Update() throws IOException, ClassNotFoundException {
        ClientConnection.getDos().writeByte(11);
        List<User> usersList;
        usersList = (List<User>) ClientConnection.getOis().readObject();
        DefaultListModel<String> model = new DefaultListModel<>();

        UList.setModel(model);
        String[] usersNames;

        if (radioBtnIsAdmin.isSelected()) {
            usersNames = usersList.stream().filter(u -> u.isIsAdmin()).map(v -> v.getUsername()).toArray(size -> new String[size]);

        } else {
            usersNames = usersList.stream().map(v -> v.getUsername()).toArray(size -> new String[size]);
        }

        for (int i = 0; i < usersNames.length; i++) {
            model.addElement(usersNames[i]);
        }
    }

    public void changeAdmin(boolean admin) {
        System.out.println(UList.getSelectedValue());
        try {
            ClientConnection.getDos().writeByte(7);
            ClientConnection.getDos().writeUTF(UList.getSelectedValue());
            ClientConnection.getDos().writeBoolean(admin);
        } catch (IOException ex) {
            Logger.getLogger(Permisos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> UList;
    private javax.swing.JScrollPane UsersList;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnConvertToAdmin;
    private javax.swing.JButton btnNoAdmin;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel panelPermisos;
    private javax.swing.JRadioButton radioBtnIsAdmin;
    // End of variables declaration//GEN-END:variables
}
