/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import data.ClientConnection;
import data.ClientHelper;
import data.Videogame;
import helpers.DateHelper;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author CARLA LLENAS
 */
public class PantallaVideojuego extends javax.swing.JFrame {

    Videogame videogame;
    private static String score;

    /**
     * Creates new form PantallaVideojuego li iniciem al constructor els labels
     * que ens indicaran la informacio del videojoc que s'ha fet clic.
     */
    public PantallaVideojuego(Videogame videogame) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.videogame = videogame;

        GameTittle.setText(videogame.getName());
        if (videogame.getCategories().size() > 0) {
            CategoryLabel.setText(videogame.getCategories().get(0).getCategory());
        } else {
            CategoryLabel.setText("Not found");
        }
        if (videogame.getPlatforms().size() > 0) {
            PlatformLabel.setText(videogame.getPlatforms().get(0).getName());
        } else {
            PlatformLabel.setText("Not found");
        }
        textAreaDescr.setText(videogame.getDescription());
        textAreaDescr.setLineWrap(true);
        textAreaDescr.setWrapStyleWord(true);
        PublisherLabel.setText(videogame.getPublisher());
        Icon icon = new ImageIcon(new ImageIcon(videogame.getGameImage()).getImage().getScaledInstance(Image.getWidth(), Image.getHeight(), java.awt.Image.SCALE_DEFAULT));
        Image.setIcon(icon);
        Icon icon1 = new ImageIcon(new ImageIcon(videogame.getGameImage()).getImage().getScaledInstance(Image1.getWidth(), Image1.getHeight(), java.awt.Image.SCALE_DEFAULT));
        Image1.setIcon(icon);
        txtFechaInicio.setText("0000/00/00");
        txtFechaFin.setText("0000/00/00");
        DateLabel.setText(DateHelper.convertDateToString(videogame.getReleaseDate()));
        labelScore.setText(videogame.getFinalScore() + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelCard = new javax.swing.JPanel();
        PanelGame = new javax.swing.JPanel();
        bntRental = new javax.swing.JButton();
        GameTittle = new javax.swing.JLabel();
        CategoryLabel = new javax.swing.JLabel();
        PlatformLabel = new javax.swing.JLabel();
        DateLabel = new javax.swing.JLabel();
        ScoreLabel = new javax.swing.JLabel();
        PublisherTittle = new javax.swing.JLabel();
        PublisherLabel = new javax.swing.JLabel();
        Image = new javax.swing.JLabel();
        btnScore = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        labelCat = new javax.swing.JLabel();
        labelDate = new javax.swing.JLabel();
        labelPlat1 = new javax.swing.JLabel();
        labelScore = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        DescriptionLabel = new javax.swing.JScrollPane();
        textAreaDescr = new javax.swing.JTextArea();
        fondoo = new javax.swing.JLabel();
        PanelScore = new javax.swing.JPanel();
        btnAtrasScore = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSaveScore = new javax.swing.JButton();
        txtNewScore = new javax.swing.JTextField();
        fondo = new javax.swing.JLabel();
        PanelRental = new javax.swing.JPanel();
        btnAlquilar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtFechaInicio = new javax.swing.JTextField();
        txtFechaFin = new javax.swing.JTextField();
        Image1 = new javax.swing.JLabel();
        fondo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelCard.setBackground(new java.awt.Color(102, 102, 0));
        PanelCard.setLayout(new java.awt.CardLayout());

        PanelGame.setBackground(new java.awt.Color(0, 0, 0));
        PanelGame.setLayout(null);

        bntRental.setBackground(new java.awt.Color(153, 255, 153));
        bntRental.setFont(new java.awt.Font("Source Sans Pro Light", 0, 18)); // NOI18N
        bntRental.setForeground(new java.awt.Color(0, 0, 0));
        bntRental.setText("Alquilar");
        bntRental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRentalActionPerformed(evt);
            }
        });
        PanelGame.add(bntRental);
        bntRental.setBounds(630, 470, 250, 42);

        GameTittle.setFont(new java.awt.Font("Source Sans Pro Light", 0, 36)); // NOI18N
        GameTittle.setForeground(new java.awt.Color(255, 255, 255));
        GameTittle.setBorder(new javax.swing.border.MatteBorder(null));
        GameTittle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PanelGame.add(GameTittle);
        GameTittle.setBounds(170, 30, 360, 47);

        CategoryLabel.setForeground(new java.awt.Color(255, 255, 255));
        CategoryLabel.setBorder(new javax.swing.border.MatteBorder(null));
        PanelGame.add(CategoryLabel);
        CategoryLabel.setBounds(47, 145, 150, 33);

        PlatformLabel.setForeground(new java.awt.Color(255, 255, 255));
        PlatformLabel.setBorder(new javax.swing.border.MatteBorder(null));
        PanelGame.add(PlatformLabel);
        PlatformLabel.setBounds(232, 145, 150, 33);

        DateLabel.setForeground(new java.awt.Color(255, 255, 255));
        DateLabel.setBorder(new javax.swing.border.MatteBorder(null));
        PanelGame.add(DateLabel);
        DateLabel.setBounds(417, 145, 150, 33);

        ScoreLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ScoreLabel.setForeground(new java.awt.Color(255, 255, 255));
        ScoreLabel.setText("SCORE");
        PanelGame.add(ScoreLabel);
        ScoreLabel.setBounds(47, 496, 76, 42);

        PublisherTittle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PublisherTittle.setForeground(new java.awt.Color(255, 255, 255));
        PublisherTittle.setText("Publisher:");
        PanelGame.add(PublisherTittle);
        PublisherTittle.setBounds(47, 453, 76, 25);

        PublisherLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PublisherLabel.setForeground(new java.awt.Color(255, 255, 255));
        PublisherLabel.setBorder(new javax.swing.border.MatteBorder(null));
        PanelGame.add(PublisherLabel);
        PublisherLabel.setBounds(141, 453, 150, 25);

        Image.setBorder(new javax.swing.border.MatteBorder(null));
        PanelGame.add(Image);
        Image.setBounds(606, 42, 291, 396);

        btnScore.setFont(new java.awt.Font("Source Sans Pro Light", 0, 14)); // NOI18N
        btnScore.setText("Añadir Puntuacion");
        btnScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScoreActionPerformed(evt);
            }
        });
        PanelGame.add(btnScore);
        btnScore.setBounds(370, 490, 153, 42);

        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        PanelGame.add(btnAtras);
        btnAtras.setBounds(39, 564, 84, 24);

        labelCat.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        labelCat.setForeground(new java.awt.Color(255, 255, 255));
        labelCat.setText("Categoria");
        PanelGame.add(labelCat);
        labelCat.setBounds(47, 107, 90, 25);

        labelDate.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        labelDate.setForeground(new java.awt.Color(255, 255, 255));
        labelDate.setText("Fecha de lanzamiento");
        PanelGame.add(labelDate);
        labelDate.setBounds(417, 107, 173, 25);

        labelPlat1.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        labelPlat1.setForeground(new java.awt.Color(255, 255, 255));
        labelPlat1.setText("Plataforma");
        PanelGame.add(labelPlat1);
        labelPlat1.setBounds(232, 107, 87, 25);

        labelScore.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        labelScore.setForeground(new java.awt.Color(255, 255, 255));
        labelScore.setBorder(new javax.swing.border.MatteBorder(null));
        PanelGame.add(labelScore);
        labelScore.setBounds(140, 500, 150, 30);

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        PanelGame.add(jSeparator2);
        jSeparator2.setBounds(40, 90, 550, 10);

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        PanelGame.add(jSeparator3);
        jSeparator3.setBounds(40, 130, 130, 10);

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        PanelGame.add(jSeparator4);
        jSeparator4.setBounds(230, 130, 130, 10);

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        PanelGame.add(jSeparator5);
        jSeparator5.setBounds(410, 130, 190, 10);

        DescriptionLabel.setBackground(new java.awt.Color(204, 204, 255));

        textAreaDescr.setEditable(false);
        textAreaDescr.setBackground(new java.awt.Color(51, 0, 51));
        textAreaDescr.setColumns(20);
        textAreaDescr.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textAreaDescr.setForeground(new java.awt.Color(255, 255, 255));
        textAreaDescr.setRows(5);
        DescriptionLabel.setViewportView(textAreaDescr);

        PanelGame.add(DescriptionLabel);
        DescriptionLabel.setBounds(40, 200, 540, 230);

        fondoo.setIcon(new javax.swing.ImageIcon("C:\\Users\\CARLA LLENAS\\OneDrive\\Documentos\\NetBeansProjects\\LudoxCliente\\src\\main\\images\\fondogameee.png")); // NOI18N
        PanelGame.add(fondoo);
        fondoo.setBounds(0, 0, 913, 600);

        PanelCard.add(PanelGame, "card2");

        PanelScore.setBackground(new java.awt.Color(204, 204, 255));
        PanelScore.setPreferredSize(new java.awt.Dimension(913, 602));
        PanelScore.setLayout(null);

        btnAtrasScore.setText("Atras");
        btnAtrasScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasScoreActionPerformed(evt);
            }
        });
        PanelScore.add(btnAtrasScore);
        btnAtrasScore.setBounds(75, 544, 73, 24);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        PanelScore.add(jSeparator1);
        jSeparator1.setBounds(45, 110, 781, 10);

        jLabel1.setFont(new java.awt.Font("Source Sans Pro Light", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Puntua el juego");
        PanelScore.add(jLabel1);
        jLabel1.setBounds(366, 67, 155, 31);

        label1.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("1 - Muy malo");
        PanelScore.add(label1);
        label1.setBounds(45, 169, 76, 18);

        label2.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setText("2 - Malo");
        PanelScore.add(label2);
        label2.setBounds(243, 169, 46, 18);

        label3.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        label3.setForeground(new java.awt.Color(255, 255, 255));
        label3.setText("3 - Bueno");
        PanelScore.add(label3);
        label3.setBounds(411, 169, 56, 18);

        label4.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        label4.setForeground(new java.awt.Color(255, 255, 255));
        label4.setText("4 - Muy Bueno");
        PanelScore.add(label4);
        label4.setBounds(589, 169, 84, 18);

        label5.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        label5.setForeground(new java.awt.Color(255, 255, 255));
        label5.setText("5 - Excelente");
        PanelScore.add(label5);
        label5.setBounds(795, 169, 74, 18);

        jLabel2.setFont(new java.awt.Font("Source Sans Pro Light", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Indica tu puntuación");
        PanelScore.add(jLabel2);
        jLabel2.setBounds(293, 300, 156, 23);

        btnSaveScore.setText("Guardar Puntuación");
        btnSaveScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveScoreActionPerformed(evt);
            }
        });
        PanelScore.add(btnSaveScore);
        btnSaveScore.setBounds(365, 432, 197, 45);

        txtNewScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewScoreActionPerformed(evt);
            }
        });
        PanelScore.add(txtNewScore);
        txtNewScore.setBounds(479, 301, 102, 24);

        fondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\CARLA LLENAS\\OneDrive\\Documentos\\NetBeansProjects\\LudoxCliente\\src\\main\\images\\fondogameee.png")); // NOI18N
        PanelScore.add(fondo);
        fondo.setBounds(0, 0, 910, 600);

        PanelCard.add(PanelScore, "card2");

        PanelRental.setBackground(new java.awt.Color(102, 153, 255));
        PanelRental.setPreferredSize(new java.awt.Dimension(913, 602));
        PanelRental.setLayout(null);

        btnAlquilar.setText("Alquilar");
        btnAlquilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlquilarActionPerformed(evt);
            }
        });
        PanelRental.add(btnAlquilar);
        btnAlquilar.setBounds(280, 350, 250, 41);

        jLabel3.setFont(new java.awt.Font("Source Serif Pro Light", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fecha fin del alquiler");
        PanelRental.add(jLabel3);
        jLabel3.setBounds(31, 197, 230, 25);

        jLabel4.setFont(new java.awt.Font("Source Serif Pro Light", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fecha inicio del alquiler");
        PanelRental.add(jLabel4);
        jLabel4.setBounds(31, 65, 202, 25);

        txtFechaInicio.setForeground(new java.awt.Color(0, 0, 0));
        PanelRental.add(txtFechaInicio);
        txtFechaInicio.setBounds(300, 70, 138, 24);

        txtFechaFin.setForeground(new java.awt.Color(0, 0, 0));
        PanelRental.add(txtFechaFin);
        txtFechaFin.setBounds(308, 199, 130, 24);

        Image1.setBorder(new javax.swing.border.MatteBorder(null));
        PanelRental.add(Image1);
        Image1.setBounds(606, 42, 291, 396);

        fondo1.setIcon(new javax.swing.ImageIcon("C:\\Users\\CARLA LLENAS\\OneDrive\\Documentos\\NetBeansProjects\\LudoxCliente\\src\\main\\images\\fondogameee.png")); // NOI18N
        PanelRental.add(fondo1);
        fondo1.setBounds(0, 0, 910, 600);

        PanelCard.add(PanelRental, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * metode del boto per tornar enrere
     *
     * @param evt
     */
    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    /**
     * metode del boto per anar a la pantalla de puntuacio
     *
     * @param evt
     */
    private void btnScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScoreActionPerformed
        // TODO add your handling code here:
        PanelCard.removeAll();
        PanelCard.add(PanelScore);
        PanelCard.repaint();
        PanelCard.revalidate();
    }//GEN-LAST:event_btnScoreActionPerformed

    /**
     * metode del boto per tornar enrere
     *
     * @param evt
     */
    private void btnAtrasScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasScoreActionPerformed
        // TODO add your handling code here:
        PanelCard.removeAll();
        PanelCard.add(PanelGame);
        PanelCard.repaint();
        PanelCard.revalidate();
    }//GEN-LAST:event_btnAtrasScoreActionPerformed

    /**
     * metode del boto per alquilar
     *
     * @param evt
     */
    private void btnAlquilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlquilarActionPerformed

        String userName = ClientHelper.userName;
        String title = ClientHelper.videogameName;
        String rentalInitial = txtFechaInicio.getText();
        String rentalFinal = txtFechaFin.getText();

        int retorno = sendRental(rentalInitial, rentalFinal, title, userName);
        if (retorno == 1 || retorno == 0) {
            if (JOptionPane.showConfirmDialog(null, retorno == 0 ? "Alquiler registrado correctamente" : "Alquiler actualizado correctamente", ClientHelper.videogameName, JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE) == 0) {
                this.dispose();
            }
        }
    }//GEN-LAST:event_btnAlquilarActionPerformed

    /**
     * metode que envia el servidor la peticio de registrar un nou alquiler d'un
     * joc concret. els parametres son: la data incial, la data de finalitzacio,
     * el nom del joc i el nom d'usuari
     *
     * @param rentalInitial
     * @param rentalFinal
     * @param title
     * @param userName
     * @return
     */
    public int sendRental(String rentalInitial, String rentalFinal, String title, String userName) {
        try {
            ClientConnection.getDos().writeByte(8);
            ClientConnection.getDos().writeUTF(userName);
            ClientConnection.getDos().writeUTF(title);
            ClientConnection.getDos().writeUTF(rentalInitial);
            ClientConnection.getDos().writeUTF(rentalFinal);
            int retorno = ClientConnection.getDis().readInt();
            return retorno;

        } catch (IOException ex) {
            Logger.getLogger(PantallaVideojuego.class.getName()).log(Level.SEVERE, "Error alquiler", ex);
            return 100;
        }
    }

    /**
     * metode del boto per anar a la pantalla d'alquilar
     *
     * @param evt
     */
    private void bntRentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRentalActionPerformed
        // TODO add your handling code here:
        PanelCard.removeAll();
        PanelCard.add(PanelRental);
        PanelCard.repaint();
        PanelCard.revalidate();
    }//GEN-LAST:event_bntRentalActionPerformed

    /**
     * metode del boto per guardar la puntuacio.
     *
     * @param evt
     */
    private void btnSaveScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveScoreActionPerformed
        // TODO add your handling code here:
        double score = ClientHelper.isScoreValid(txtNewScore.getText());
        String userName = ClientHelper.userName;
        String title = ClientHelper.videogameName;
        double scoreDouble = Double.parseDouble(txtNewScore.getText());
        int retorno = sendScore(scoreDouble, title, userName);
        if (score != 1) {
            // TODO add your handling code here:
            if (retorno == 1 || retorno == 0) {
                try {
                    videogame = (Videogame) ClientConnection.getOis().readObject();
                    update();
                    if (JOptionPane.showConfirmDialog(null, retorno == 0 ? "Puntuacion registrada correctamente" : "Puntuacion actualizada correctamente", ClientHelper.videogameName, JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE) == 0) {
                        this.dispose();
                    }
                } catch (IOException ex) {
                    Logger.getLogger(PantallaVideojuego.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(PantallaVideojuego.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "El valor debe ser entre 0 y 10", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSaveScoreActionPerformed

    /**
     * metode que envia al servidor la petició de registrar una nova puntuació a
     * un joc concret. els parametres son: la puntuacio, el nom del joc i
     * l'username
     *
     * @param scoreDouble
     * @param title
     * @param userName
     * @return
     */
    public int sendScore(Double scoreDouble, String title, String userName) {
        try {
            ClientConnection.getDos().writeByte(9);
            ClientConnection.getDos().writeUTF(userName);
            ClientConnection.getDos().writeUTF(title);
            ClientConnection.getDos().writeDouble(scoreDouble);
            int retorno = ClientConnection.getDis().readInt();
            return retorno;

        } catch (IOException ex) {
            Logger.getLogger(PantallaVideojuego.class.getName()).log(Level.SEVERE, "Error alquiler", ex);
            return 100;
        }
    }

    private void txtNewScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewScoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewScoreActionPerformed

    /**
     * metode que fa actualizació de la puntuació feta per l'usuari
     */
    private void update() {
        labelScore.setText(videogame.getFinalScore() + "");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CategoryLabel;
    private javax.swing.JLabel DateLabel;
    private javax.swing.JScrollPane DescriptionLabel;
    private javax.swing.JLabel GameTittle;
    private javax.swing.JLabel Image;
    private javax.swing.JLabel Image1;
    private javax.swing.JPanel PanelCard;
    private javax.swing.JPanel PanelGame;
    private javax.swing.JPanel PanelRental;
    private javax.swing.JPanel PanelScore;
    private javax.swing.JLabel PlatformLabel;
    private javax.swing.JLabel PublisherLabel;
    private javax.swing.JLabel PublisherTittle;
    private javax.swing.JLabel ScoreLabel;
    private javax.swing.JButton bntRental;
    private javax.swing.JButton btnAlquilar;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnAtrasScore;
    private javax.swing.JButton btnSaveScore;
    private javax.swing.JButton btnScore;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel fondo1;
    private javax.swing.JLabel fondoo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel labelCat;
    private javax.swing.JLabel labelDate;
    private javax.swing.JLabel labelPlat1;
    private javax.swing.JLabel labelScore;
    private javax.swing.JTextArea textAreaDescr;
    private javax.swing.JTextField txtFechaFin;
    private javax.swing.JTextField txtFechaInicio;
    private javax.swing.JTextField txtNewScore;
    // End of variables declaration//GEN-END:variables
}
