/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import data.Videogame;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author CARLA LLENAS
 */
public class PantallaVideojuego extends javax.swing.JFrame {

    Videogame videogame = new Videogame();
    /**
     * Creates new form PantallaVideojuego
     */
    public PantallaVideojuego() {
        initComponents();
        GameTittle.setText(videogame.getName());
        //CategoryLabel.setText(videogame.);
        //PlatfromLabel.setText(videogame.);
        DescriptionLabel.setText(videogame.getDescription());
        PublisherLabel.setText(videogame.getPublisher());
        //Image.setIcon(videogame.getGameImage());      
        
        txtFechaInicio.setText(fechaActual());
        txtFechaFin.setText("00/00/0000");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelCard = new javax.swing.JPanel();
        PanelGame = new javax.swing.JPanel();
        bntRental = new javax.swing.JButton();
        GameTittle = new javax.swing.JLabel();
        CategoryLabel = new javax.swing.JLabel();
        PlatfromLabel = new javax.swing.JLabel();
        DescriptionLabel = new javax.swing.JLabel();
        DateLabel = new javax.swing.JLabel();
        ScoreLabel = new javax.swing.JLabel();
        PublisherTittle = new javax.swing.JLabel();
        PublisherLabel = new javax.swing.JLabel();
        Image = new javax.swing.JLabel();
        btnScore = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        PanelScore = new javax.swing.JPanel();
        btnAtrasScore = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnSaveScore = new javax.swing.JButton();
        PanelRental = new javax.swing.JPanel();
        btnAlquilar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtFechaInicio = new javax.swing.JTextField();
        txtFechaFin = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelCard.setBackground(new java.awt.Color(102, 102, 0));
        PanelCard.setLayout(new java.awt.CardLayout());

        PanelGame.setBackground(new java.awt.Color(102, 153, 255));

        bntRental.setText("Alquilar");

        GameTittle.setForeground(new java.awt.Color(0, 0, 0));
        GameTittle.setBorder(new javax.swing.border.MatteBorder(null));

        CategoryLabel.setForeground(new java.awt.Color(0, 0, 0));
        CategoryLabel.setBorder(new javax.swing.border.MatteBorder(null));

        PlatfromLabel.setForeground(new java.awt.Color(0, 0, 0));
        PlatfromLabel.setBorder(new javax.swing.border.MatteBorder(null));

        DescriptionLabel.setForeground(new java.awt.Color(0, 0, 0));
        DescriptionLabel.setBorder(new javax.swing.border.MatteBorder(null));

        DateLabel.setForeground(new java.awt.Color(0, 0, 0));
        DateLabel.setBorder(new javax.swing.border.MatteBorder(null));

        ScoreLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ScoreLabel.setForeground(new java.awt.Color(0, 0, 0));
        ScoreLabel.setText("SCORE");

        PublisherTittle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PublisherTittle.setForeground(new java.awt.Color(0, 0, 0));
        PublisherTittle.setText("Publisher:");

        PublisherLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PublisherLabel.setForeground(new java.awt.Color(0, 0, 0));
        PublisherLabel.setBorder(new javax.swing.border.MatteBorder(null));

        Image.setBorder(new javax.swing.border.MatteBorder(null));

        btnScore.setText("Añadir Puntuacion");
        btnScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScoreActionPerformed(evt);
            }
        });

        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelGameLayout = new javax.swing.GroupLayout(PanelGame);
        PanelGame.setLayout(PanelGameLayout);
        PanelGameLayout.setHorizontalGroup(
            PanelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGameLayout.createSequentialGroup()
                .addGroup(PanelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelGameLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(PanelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GameTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelGameLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(PanelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelGameLayout.createSequentialGroup()
                                        .addComponent(CategoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)
                                        .addComponent(PlatfromLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(45, 45, 45)
                                        .addComponent(DateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(DescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(Image, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelGameLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(PanelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelGameLayout.createSequentialGroup()
                                .addComponent(PublisherTittle)
                                .addGap(18, 18, 18)
                                .addComponent(PublisherLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(365, 365, 365)
                                .addComponent(bntRental, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelGameLayout.createSequentialGroup()
                                .addComponent(ScoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(230, 230, 230)
                                .addComponent(btnScore, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        PanelGameLayout.setVerticalGroup(
            PanelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGameLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(PanelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelGameLayout.createSequentialGroup()
                        .addComponent(GameTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addGroup(PanelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CategoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PlatfromLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addComponent(DescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Image, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(PanelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelGameLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(bntRental, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelGameLayout.createSequentialGroup()
                        .addComponent(PublisherTittle)
                        .addGap(18, 18, 18)
                        .addComponent(ScoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelGameLayout.createSequentialGroup()
                        .addComponent(PublisherLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnScore, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(btnAtras)
                .addGap(14, 14, 14))
        );

        PanelCard.add(PanelGame, "card2");

        PanelScore.setBackground(new java.awt.Color(204, 204, 255));

        btnAtrasScore.setText("Atras");
        btnAtrasScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasScoreActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Source Sans Pro Light", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Puntua el juego");

        label1.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        label1.setForeground(new java.awt.Color(0, 0, 0));
        label1.setText("1 - Muy malo");

        label2.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        label2.setForeground(new java.awt.Color(0, 0, 0));
        label2.setText("2 - Malo");

        label3.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        label3.setForeground(new java.awt.Color(0, 0, 0));
        label3.setText("3 - Bueno");

        label4.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        label4.setForeground(new java.awt.Color(0, 0, 0));
        label4.setText("4 - Muy Bueno");

        label5.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        label5.setForeground(new java.awt.Color(0, 0, 0));
        label5.setText("5 - Excelente");

        jLabel2.setFont(new java.awt.Font("Source Sans Pro Light", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Indica tu puntuación");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        btnSaveScore.setText("Guardar Puntuación");

        javax.swing.GroupLayout PanelScoreLayout = new javax.swing.GroupLayout(PanelScore);
        PanelScore.setLayout(PanelScoreLayout);
        PanelScoreLayout.setHorizontalGroup(
            PanelScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelScoreLayout.createSequentialGroup()
                .addGroup(PanelScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelScoreLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(btnAtrasScore, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelScoreLayout.createSequentialGroup()
                        .addGap(366, 366, 366)
                        .addComponent(jLabel1))
                    .addGroup(PanelScoreLayout.createSequentialGroup()
                        .addContainerGap(39, Short.MAX_VALUE)
                        .addGroup(PanelScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 781, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelScoreLayout.createSequentialGroup()
                                .addGroup(PanelScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelScoreLayout.createSequentialGroup()
                                        .addComponent(label1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                                        .addComponent(label2)
                                        .addGap(122, 122, 122)
                                        .addComponent(label3))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelScoreLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)))
                                .addGap(122, 122, 122)
                                .addComponent(label4)
                                .addGap(122, 122, 122)
                                .addComponent(label5)))))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelScoreLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(354, 354, 354))
            .addGroup(PanelScoreLayout.createSequentialGroup()
                .addGap(365, 365, 365)
                .addComponent(btnSaveScore, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelScoreLayout.setVerticalGroup(
            PanelScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelScoreLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(PanelScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label1)
                    .addComponent(label2)
                    .addComponent(label3)
                    .addComponent(label4)
                    .addComponent(label5))
                .addGap(113, 113, 113)
                .addGroup(PanelScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(btnSaveScore, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(btnAtrasScore)
                .addGap(34, 34, 34))
        );

        PanelCard.add(PanelScore, "card2");

        PanelRental.setBackground(new java.awt.Color(102, 153, 255));

        btnAlquilar.setText("Alquilar");
        btnAlquilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlquilarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Source Serif Pro Light", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Fecha fin del alquiler");

        jLabel4.setFont(new java.awt.Font("Source Serif Pro Light", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Fecha inicio del alquiler");

        txtFechaInicio.setEditable(false);
        txtFechaInicio.setForeground(new java.awt.Color(0, 0, 0));

        txtFechaFin.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout PanelRentalLayout = new javax.swing.GroupLayout(PanelRental);
        PanelRental.setLayout(PanelRentalLayout);
        PanelRentalLayout.setHorizontalGroup(
            PanelRentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRentalLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addGap(62, 62, 62)
                .addGroup(PanelRentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelRentalLayout.createSequentialGroup()
                        .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(61, Short.MAX_VALUE))
                    .addGroup(PanelRentalLayout.createSequentialGroup()
                        .addComponent(txtFechaFin)
                        .addGap(54, 54, 54))))
            .addGroup(PanelRentalLayout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(btnAlquilar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(PanelRentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelRentalLayout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(jLabel4)
                    .addContainerGap(235, Short.MAX_VALUE)))
        );
        PanelRentalLayout.setVerticalGroup(
            PanelRentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelRentalLayout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(PanelRentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(btnAlquilar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
            .addGroup(PanelRentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelRentalLayout.createSequentialGroup()
                    .addGap(65, 65, 65)
                    .addComponent(jLabel4)
                    .addContainerGap(186, Short.MAX_VALUE)))
        );

        PanelCard.add(PanelRental, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        new Principal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScoreActionPerformed
        // TODO add your handling code here:
        PanelCard.removeAll();
        PanelCard.add(PanelScore);
        PanelCard.repaint();
        PanelCard.revalidate();
    }//GEN-LAST:event_btnScoreActionPerformed

    private void btnAtrasScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasScoreActionPerformed
        // TODO add your handling code here:
        PanelCard.removeAll();
        PanelCard.add(PanelGame);
        PanelCard.repaint();
        PanelCard.revalidate();
    }//GEN-LAST:event_btnAtrasScoreActionPerformed

    private void btnAlquilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlquilarActionPerformed
        // TODO add your handling code here:
        
        
        PanelCard.removeAll();
        PanelCard.add(PanelGame);
        PanelCard.repaint();
        PanelCard.revalidate();
    }//GEN-LAST:event_btnAlquilarActionPerformed

    public String fechaActual(){
     Date date = new Date();
     SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/YYYY");
     return dateFormat.format(date);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CategoryLabel;
    private javax.swing.JLabel DateLabel;
    private javax.swing.JLabel DescriptionLabel;
    private javax.swing.JLabel GameTittle;
    private javax.swing.JLabel Image;
    private javax.swing.JPanel PanelCard;
    private javax.swing.JPanel PanelGame;
    private javax.swing.JPanel PanelRental;
    private javax.swing.JPanel PanelScore;
    private javax.swing.JLabel PlatfromLabel;
    private javax.swing.JLabel PublisherLabel;
    private javax.swing.JLabel PublisherTittle;
    private javax.swing.JLabel ScoreLabel;
    private javax.swing.JButton bntRental;
    private javax.swing.JButton btnAlquilar;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnAtrasScore;
    private javax.swing.JButton btnSaveScore;
    private javax.swing.JButton btnScore;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JTextField txtFechaFin;
    private javax.swing.JTextField txtFechaInicio;
    // End of variables declaration//GEN-END:variables
}
