package forms;

import forms.admin.MenuAdmin;
import data.User;
import java.awt.CardLayout;
import java.awt.event.ActionListener;
import java.net.Socket;
import javax.swing.JPanel;

/**
 *
 * @author CARLA LLENAS
 */
public class Principal extends javax.swing.JFrame {

    private JPanel contentPanel;
    final static String PANEL1 = "Panel 1 ";
    final static String PANEL2 = "Panel 2 ";
    
    NewJPanel jPanel = new NewJPanel();
    NewJPanel2 jPanel2 = new NewJPanel2();
            
    login log = new login();
    User user;
    registro reg;

    /**
     * constructor de la classe. verificarà també si l'usuari entrat es admin o
     * no
     *
     * @param log paramentre d'objecte de la clase login
     * @param user paramentre de l'usuari de la clase User
     */
    public Principal(login log, User user) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.log = log;
        this.user = user;

        if (!user.isIsAdmin()) {
            btnAdmin.setVisible(false);
        }
        this.setLocationRelativeTo(null);
    }

    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        contentPanel.add(jPanel, PANEL1);
        contentPanel.add(jPanel2, PANEL2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelVentana = new javax.swing.JPanel();
        panelMenu = new javax.swing.JPanel();
        panelTittle = new javax.swing.JPanel();
        labelTittle = new javax.swing.JLabel();
        panelAlquiler = new javax.swing.JPanel();
        logoAlquiler = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panelVideojuegos = new javax.swing.JPanel();
        logoJuegos = new javax.swing.JLabel();
        labelVideojuegos = new javax.swing.JLabel();
        panelAjustes = new javax.swing.JPanel();
        logoAjustes = new javax.swing.JLabel();
        labelAjustes = new javax.swing.JLabel();
        panelReseñas = new javax.swing.JPanel();
        logoReseñas = new javax.swing.JLabel();
        labelReseñas = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnAdmin = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuPrincipal = new javax.swing.JMenu();
        menuSalir = new javax.swing.JMenu();
        itemLogout = new javax.swing.JMenuItem();
        itemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ludox Menu");
        setBackground(new java.awt.Color(0, 0, 0));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.black);
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new java.awt.CardLayout());

        panelVentana.setBackground(new java.awt.Color(255, 255, 255));

        panelMenu.setBackground(new java.awt.Color(0, 0, 0));

        panelTittle.setBackground(new java.awt.Color(0, 0, 0));

        labelTittle.setBackground(new java.awt.Color(0, 0, 0));
        labelTittle.setFont(new java.awt.Font("Liberation Sans Narrow", 0, 48)); // NOI18N
        labelTittle.setForeground(new java.awt.Color(153, 0, 204));
        labelTittle.setText("Ludox");
        labelTittle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelTittleLayout = new javax.swing.GroupLayout(panelTittle);
        panelTittle.setLayout(panelTittleLayout);
        panelTittleLayout.setHorizontalGroup(
            panelTittleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTittleLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(labelTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTittleLayout.setVerticalGroup(
            panelTittleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTittleLayout.createSequentialGroup()
                .addGap(0, 38, Short.MAX_VALUE)
                .addComponent(labelTittle))
        );

        panelAlquiler.setBackground(new java.awt.Color(153, 102, 255));

        logoAlquiler.setIcon(new javax.swing.ImageIcon("C:\\Users\\CARLA LLENAS\\OneDrive\\Documentos\\NetBeansProjects\\LudoxCliente\\src\\main\\images\\icons8-carrito-de-la-compra-cargado-48.png")); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Alquileres");

        javax.swing.GroupLayout panelAlquilerLayout = new javax.swing.GroupLayout(panelAlquiler);
        panelAlquiler.setLayout(panelAlquilerLayout);
        panelAlquilerLayout.setHorizontalGroup(
            panelAlquilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlquilerLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(logoAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAlquilerLayout.setVerticalGroup(
            panelAlquilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoAlquiler, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
            .addGroup(panelAlquilerLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelVideojuegos.setBackground(new java.awt.Color(153, 0, 255));
        panelVideojuegos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelVideojuegosMouseClicked(evt);
            }
        });

        logoJuegos.setIcon(new javax.swing.ImageIcon("C:\\Users\\CARLA LLENAS\\OneDrive\\Documentos\\NetBeansProjects\\LudoxCliente\\src\\main\\images\\icons8-battle-64.png")); // NOI18N

        labelVideojuegos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelVideojuegos.setForeground(new java.awt.Color(0, 0, 0));
        labelVideojuegos.setText("Videojuegos");
        labelVideojuegos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelVideojuegosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelVideojuegosLayout = new javax.swing.GroupLayout(panelVideojuegos);
        panelVideojuegos.setLayout(panelVideojuegosLayout);
        panelVideojuegosLayout.setHorizontalGroup(
            panelVideojuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVideojuegosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoJuegos)
                .addGap(38, 38, 38)
                .addComponent(labelVideojuegos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelVideojuegosLayout.setVerticalGroup(
            panelVideojuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoJuegos)
            .addGroup(panelVideojuegosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(labelVideojuegos))
        );

        panelAjustes.setBackground(new java.awt.Color(153, 102, 255));

        logoAjustes.setIcon(new javax.swing.ImageIcon("C:\\Users\\CARLA LLENAS\\OneDrive\\Documentos\\NetBeansProjects\\LudoxCliente\\src\\main\\images\\icons8-engranajes-50.png")); // NOI18N

        labelAjustes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelAjustes.setForeground(new java.awt.Color(0, 0, 0));
        labelAjustes.setText("Ajustes");

        javax.swing.GroupLayout panelAjustesLayout = new javax.swing.GroupLayout(panelAjustes);
        panelAjustes.setLayout(panelAjustesLayout);
        panelAjustesLayout.setHorizontalGroup(
            panelAjustesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAjustesLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(logoAjustes, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelAjustes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAjustesLayout.setVerticalGroup(
            panelAjustesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAjustesLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(labelAjustes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(logoAjustes, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
        );

        panelReseñas.setBackground(new java.awt.Color(153, 0, 255));

        logoReseñas.setIcon(new javax.swing.ImageIcon("C:\\Users\\CARLA LLENAS\\OneDrive\\Documentos\\NetBeansProjects\\LudoxCliente\\src\\main\\images\\icons8-mano-con-pluma-50.png")); // NOI18N

        labelReseñas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelReseñas.setForeground(new java.awt.Color(0, 0, 0));
        labelReseñas.setText("Mis reseñas");
        labelReseñas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                labelReseñasKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panelReseñasLayout = new javax.swing.GroupLayout(panelReseñas);
        panelReseñas.setLayout(panelReseñasLayout);
        panelReseñasLayout.setHorizontalGroup(
            panelReseñasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReseñasLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(logoReseñas, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(labelReseñas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelReseñasLayout.setVerticalGroup(
            panelReseñasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoReseñas, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
            .addGroup(panelReseñasLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(labelReseñas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSeparator1.setForeground(new java.awt.Color(153, 102, 255));
        jSeparator1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        btnAdmin.setBackground(new java.awt.Color(255, 255, 255));
        btnAdmin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnAdmin.setText("ADMINISTRADOR");
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTittle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelVideojuegos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelAlquiler, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelReseñas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelAjustes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(btnAdmin)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTittle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(panelVideojuegos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelReseñas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelAjustes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(btnAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout panelVentanaLayout = new javax.swing.GroupLayout(panelVentana);
        panelVentana.setLayout(panelVentanaLayout);
        panelVentanaLayout.setHorizontalGroup(
            panelVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVentanaLayout.createSequentialGroup()
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 694, Short.MAX_VALUE))
        );
        panelVentanaLayout.setVerticalGroup(
            panelVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(panelVentana, "card2");

        jMenuBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 0, 204), null, null));
        jMenuBar1.setAlignmentX(20.0F);
        jMenuBar1.setAlignmentY(20.0F);
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jMenuBar1.setName(""); // NOI18N

        menuPrincipal.setForeground(new java.awt.Color(0, 0, 0));
        menuPrincipal.setText("INICIO");
        jMenuBar1.add(menuPrincipal);

        menuSalir.setForeground(new java.awt.Color(0, 0, 0));
        menuSalir.setText("SALIR");

        itemLogout.setForeground(new java.awt.Color(255, 51, 255));
        itemLogout.setText("Log Out");
        itemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemLogoutActionPerformed(evt);
            }
        });
        menuSalir.add(itemLogout);

        itemSalir.setForeground(new java.awt.Color(255, 0, 102));
        itemSalir.setText("Salir");
        itemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSalirActionPerformed(evt);
            }
        });
        menuSalir.add(itemSalir);

        jMenuBar1.add(menuSalir);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLogoutActionPerformed
        log.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itemLogoutActionPerformed

    private void itemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_itemSalirActionPerformed

    private void labelReseñasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_labelReseñasKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_labelReseñasKeyPressed

    private void labelVideojuegosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelVideojuegosMouseClicked
        // TODO add your handling code here:
        Videogames videogames = new Videogames();
        videogames.setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_labelVideojuegosMouseClicked

    private void panelVideojuegosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelVideojuegosMouseClicked
        // TODO add your handling code here:
        Videogames videogames = new Videogames();
        videogames.setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_panelVideojuegosMouseClicked

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        // TODO add your handling code here:
//        jPanel.btnAltaVideojuegos.addActionListener(new ActionListener()){
//        CardLayout cl = (CardLayout)(contentPanel.getLayout());
//        cl.show(contentPanel, PANEL2);
//        }     
        
//        MenuAdmin menuAdmin = new MenuAdmin();
//        menuAdmin.setVisible(true);
////        this.setVisible(false);
    }//GEN-LAST:event_btnAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmin;
    private javax.swing.JMenuItem itemLogout;
    private javax.swing.JMenuItem itemSalir;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelAjustes;
    private javax.swing.JLabel labelReseñas;
    private javax.swing.JLabel labelTittle;
    private javax.swing.JLabel labelVideojuegos;
    private javax.swing.JLabel logoAjustes;
    private javax.swing.JLabel logoAlquiler;
    private javax.swing.JLabel logoJuegos;
    private javax.swing.JLabel logoReseñas;
    private javax.swing.JMenu menuPrincipal;
    private javax.swing.JMenu menuSalir;
    private javax.swing.JPanel panelAjustes;
    private javax.swing.JPanel panelAlquiler;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelReseñas;
    private javax.swing.JPanel panelTittle;
    private javax.swing.JPanel panelVentana;
    private javax.swing.JPanel panelVideojuegos;
    // End of variables declaration//GEN-END:variables

}
