package forms;

import data.ClientConnection;
import helpers.EditUser;
import data.ClientHelper;
import helpers.QueryFilter;
import data.User;
import data.Videogame;
import encrypt.Encrypter;
import forms.admin.AltaVideojuegos;
import forms.admin.ControlUsuarios;
import forms.admin.EditarVideojuegos;
import forms.admin.Permisos;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author CARLA LLENAS
 */


public class Principal extends javax.swing.JFrame {

    private static Videogame videogames;
    private static int totalPaginas;
    private static int ActualPage = 1;

    login log = new login();
    User user;
    registro reg;
    Permisos per = new Permisos();

    //cANTIDAD IMAGENES + 1
    ImageIcon img[] = new ImageIcon[5];
    int contador = 1;

    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * constructor de la classe. verificarà també si l'usuari entrat es admin o
     * no
     *
     * @param log paramentre d'objecte de la clase login
     * @param user paramentre de l'usuari de la clase User
     */
    public Principal(login log, User user) {
        initComponents();
        try {
            getTop5();
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setLocationRelativeTo(null);
        this.log = log;
        this.user = user;

        if (!user.isIsAdmin()) {
            btnAdmin.setVisible(false);
        }
        this.setLocationRelativeTo(null);

        for (int i = 0; i < 5; i++) {
            img[i] = new ImageIcon(getClass().getResource("/carrusel/" + i + ".png"));
        }
        carruselLabel.setIcon(img[1]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        panelTittle = new javax.swing.JPanel();
        labelTittle = new javax.swing.JLabel();
        panelAlquiler = new javax.swing.JPanel();
        logoAlquiler = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panelVideojuegos = new javax.swing.JPanel();
        logoJuegos = new javax.swing.JLabel();
        labelVideojuegos = new javax.swing.JLabel();
        panelAjustes = new javax.swing.JPanel();
        logoAjustes = new javax.swing.JLabel();
        labelAjustes = new javax.swing.JLabel();
        panelReseñas = new javax.swing.JPanel();
        logoReseñas = new javax.swing.JLabel();
        labelReseñas = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnAdmin = new javax.swing.JButton();
        PanelVentana = new javax.swing.JPanel();
        PanelPrincipal = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        GamesList = new javax.swing.JList<>();
        carruselLabel = new javax.swing.JLabel();
        btnIZQ = new javax.swing.JButton();
        btnAUTO = new javax.swing.JButton();
        btnDER = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        labelFondoo = new javax.swing.JLabel();
        PanelVideojuegos = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        panelICONSearch = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        labelFiltros = new javax.swing.JLabel();
        panelPlataforma = new javax.swing.JPanel();
        radioBtnPS = new javax.swing.JRadioButton();
        radioBtnXBOX = new javax.swing.JRadioButton();
        radioBtnNintendo = new javax.swing.JRadioButton();
        panelDate = new javax.swing.JPanel();
        radioBtnMinDate = new javax.swing.JRadioButton();
        radioBtnMaxDate = new javax.swing.JRadioButton();
        panelScore = new javax.swing.JPanel();
        radioBtnMaxScore = new javax.swing.JRadioButton();
        radioBtnMinScore = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        btnFiltrar = new javax.swing.JButton();
        btnQuitarFiltros = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TotalGamesList = new javax.swing.JList<>();
        btnFirstPage = new javax.swing.JButton();
        btnPageBefore = new javax.swing.JButton();
        btnLastPage = new javax.swing.JButton();
        btnNextPage = new javax.swing.JButton();
        labelNumPage = new javax.swing.JLabel();
        PanelMenuAdmin = new javax.swing.JPanel();
        btnAltaVideojuegos = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnUsuarios = new javax.swing.JButton();
        btnEditVideojuegos = new javax.swing.JButton();
        btnPermisos = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        labelFondo = new javax.swing.JLabel();
        PanelAjustes = new javax.swing.JPanel();
        labelNombreApell = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        txtNameEdit = new javax.swing.JTextField();
        txtMailEdit = new javax.swing.JTextField();
        txtPassEdit = new javax.swing.JTextField();
        btnLogout = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        labelFondoo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ludox Menu");
        setBackground(new java.awt.Color(0, 0, 0));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.black);
        setLocationByPlatform(true);
        setUndecorated(true);

        panelMenu.setBackground(new java.awt.Color(0, 0, 0));
        panelMenu.setLayout(null);

        panelTittle.setBackground(new java.awt.Color(0, 0, 0));

        labelTittle.setBackground(new java.awt.Color(0, 0, 0));
        labelTittle.setFont(new java.awt.Font("Liberation Sans Narrow", 0, 48)); // NOI18N
        labelTittle.setForeground(new java.awt.Color(255, 255, 255));
        labelTittle.setText("Ludox");
        labelTittle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelTittle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelTittleMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelTittleLayout = new javax.swing.GroupLayout(panelTittle);
        panelTittle.setLayout(panelTittleLayout);
        panelTittleLayout.setHorizontalGroup(
            panelTittleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTittleLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(labelTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTittleLayout.setVerticalGroup(
            panelTittleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTittleLayout.createSequentialGroup()
                .addGap(0, 38, Short.MAX_VALUE)
                .addComponent(labelTittle))
        );

        panelMenu.add(panelTittle);
        panelTittle.setBounds(0, 6, 307, 90);

        panelAlquiler.setBackground(new java.awt.Color(102, 102, 255));

        logoAlquiler.setIcon(new javax.swing.ImageIcon("C:\\Users\\CARLA LLENAS\\OneDrive\\Documentos\\NetBeansProjects\\LudoxCliente\\src\\main\\images\\icons8-carrito-de-la-compra-cargado-48.png")); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Alquileres");

        javax.swing.GroupLayout panelAlquilerLayout = new javax.swing.GroupLayout(panelAlquiler);
        panelAlquiler.setLayout(panelAlquilerLayout);
        panelAlquilerLayout.setHorizontalGroup(
            panelAlquilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlquilerLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(logoAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAlquilerLayout.setVerticalGroup(
            panelAlquilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoAlquiler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelAlquilerLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        panelMenu.add(panelAlquiler);
        panelAlquiler.setBounds(0, 247, 307, 62);

        panelVideojuegos.setBackground(new java.awt.Color(102, 0, 204));
        panelVideojuegos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelVideojuegosMouseClicked(evt);
            }
        });

        logoJuegos.setIcon(new javax.swing.ImageIcon("C:\\Users\\CARLA LLENAS\\OneDrive\\Documentos\\NetBeansProjects\\LudoxCliente\\src\\main\\images\\icons8-battle-64.png")); // NOI18N

        labelVideojuegos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelVideojuegos.setForeground(new java.awt.Color(0, 0, 0));
        labelVideojuegos.setText("Videojuegos");
        labelVideojuegos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelVideojuegosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelVideojuegosLayout = new javax.swing.GroupLayout(panelVideojuegos);
        panelVideojuegos.setLayout(panelVideojuegosLayout);
        panelVideojuegosLayout.setHorizontalGroup(
            panelVideojuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVideojuegosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoJuegos)
                .addGap(38, 38, 38)
                .addComponent(labelVideojuegos)
                .addContainerGap(94, Short.MAX_VALUE))
        );
        panelVideojuegosLayout.setVerticalGroup(
            panelVideojuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoJuegos)
            .addGroup(panelVideojuegosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(labelVideojuegos))
        );

        panelMenu.add(panelVideojuegos);
        panelVideojuegos.setBounds(0, 177, 307, 64);

        panelAjustes.setBackground(new java.awt.Color(102, 102, 255));
        panelAjustes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelAjustesMouseClicked(evt);
            }
        });

        logoAjustes.setIcon(new javax.swing.ImageIcon("C:\\Users\\CARLA LLENAS\\OneDrive\\Documentos\\NetBeansProjects\\LudoxCliente\\src\\main\\images\\icons8-engranajes-50.png")); // NOI18N

        labelAjustes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelAjustes.setForeground(new java.awt.Color(0, 0, 0));
        labelAjustes.setText("Ajustes");
        labelAjustes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAjustesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelAjustesLayout = new javax.swing.GroupLayout(panelAjustes);
        panelAjustes.setLayout(panelAjustesLayout);
        panelAjustesLayout.setHorizontalGroup(
            panelAjustesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAjustesLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(logoAjustes, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelAjustes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAjustesLayout.setVerticalGroup(
            panelAjustesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAjustesLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(labelAjustes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(logoAjustes, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
        );

        panelMenu.add(panelAjustes);
        panelAjustes.setBounds(0, 383, 307, 61);

        panelReseñas.setBackground(new java.awt.Color(102, 0, 204));

        logoReseñas.setIcon(new javax.swing.ImageIcon("C:\\Users\\CARLA LLENAS\\OneDrive\\Documentos\\NetBeansProjects\\LudoxCliente\\src\\main\\images\\icons8-mano-con-pluma-50.png")); // NOI18N

        labelReseñas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelReseñas.setForeground(new java.awt.Color(0, 0, 0));
        labelReseñas.setText("Mis reseñas");
        labelReseñas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                labelReseñasKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panelReseñasLayout = new javax.swing.GroupLayout(panelReseñas);
        panelReseñas.setLayout(panelReseñasLayout);
        panelReseñasLayout.setHorizontalGroup(
            panelReseñasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReseñasLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(logoReseñas, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(labelReseñas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelReseñasLayout.setVerticalGroup(
            panelReseñasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoReseñas, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
            .addGroup(panelReseñasLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(labelReseñas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelMenu.add(panelReseñas);
        panelReseñas.setBounds(0, 315, 307, 62);

        jSeparator1.setForeground(new java.awt.Color(102, 0, 204));
        jSeparator1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        panelMenu.add(jSeparator1);
        jSeparator1.setBounds(18, 102, 242, 10);

        btnAdmin.setBackground(new java.awt.Color(0, 0, 153));
        btnAdmin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnAdmin.setText("ADMINISTRADOR");
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });
        panelMenu.add(btnAdmin);
        btnAdmin.setBounds(60, 670, 190, 49);

        PanelVentana.setBackground(new java.awt.Color(255, 255, 255));
        PanelVentana.setLayout(new java.awt.CardLayout());

        PanelPrincipal.setBackground(new java.awt.Color(204, 204, 204));
        PanelPrincipal.setPreferredSize(new java.awt.Dimension(840, 800));
        PanelPrincipal.setLayout(null);

        GamesList.setBackground(new java.awt.Color(102, 102, 255));
        GamesList.setForeground(new java.awt.Color(0, 0, 0));
        GamesList.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                GamesListAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane2.setViewportView(GamesList);

        PanelPrincipal.add(jScrollPane2);
        jScrollPane2.setBounds(580, 100, 226, 240);

        carruselLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelPrincipal.add(carruselLabel);
        carruselLabel.setBounds(39, 40, 500, 690);

        btnIZQ.setText("jButton1");
        btnIZQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIZQActionPerformed(evt);
            }
        });
        PanelPrincipal.add(btnIZQ);
        btnIZQ.setBounds(39, 748, 57, 24);

        btnAUTO.setText("jButton2");
        btnAUTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAUTOActionPerformed(evt);
            }
        });
        PanelPrincipal.add(btnAUTO);
        btnAUTO.setBounds(228, 748, 57, 24);

        btnDER.setText("jButton3");
        btnDER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDERActionPerformed(evt);
            }
        });
        PanelPrincipal.add(btnDER);
        btnDER.setBounds(424, 748, 57, 24);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("NUEVOS AÑADIDOS");
        PanelPrincipal.add(jLabel10);
        jLabel10.setBounds(590, 480, 230, 50);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("TOP 5 VIDEOJUEGOS");
        PanelPrincipal.add(jLabel14);
        jLabel14.setBounds(580, 50, 230, 50);

        labelFondoo.setForeground(new java.awt.Color(0, 0, 0));
        labelFondoo.setIcon(new javax.swing.ImageIcon("C:\\Users\\CARLA LLENAS\\OneDrive\\Documentos\\NetBeansProjects\\LudoxCliente\\src\\main\\images\\fondoprincipalbueno.png")); // NOI18N
        PanelPrincipal.add(labelFondoo);
        labelFondoo.setBounds(1, -1, 850, 800);

        PanelVentana.add(PanelPrincipal, "card4");

        PanelVideojuegos.setBackground(new java.awt.Color(204, 153, 255));
        PanelVideojuegos.setMaximumSize(new java.awt.Dimension(850, 800));

        panelICONSearch.setBackground(new java.awt.Color(204, 153, 255));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\CARLA LLENAS\\OneDrive\\Documentos\\NetBeansProjects\\LudoxCliente\\src\\main\\images\\icons8-búsqueda-64.png")); // NOI18N

        javax.swing.GroupLayout panelICONSearchLayout = new javax.swing.GroupLayout(panelICONSearch);
        panelICONSearch.setLayout(panelICONSearchLayout);
        panelICONSearchLayout.setHorizontalGroup(
            panelICONSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelICONSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelICONSearchLayout.setVerticalGroup(
            panelICONSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelICONSearchLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        labelFiltros.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelFiltros.setForeground(new java.awt.Color(0, 0, 0));
        labelFiltros.setText("FILTROS");

        panelPlataforma.setBackground(new java.awt.Color(204, 153, 255));
        panelPlataforma.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Plataforma", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        panelPlataforma.setForeground(new java.awt.Color(0, 0, 0));

        radioBtnPS.setText("Play Station");
        radioBtnPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnPSActionPerformed(evt);
            }
        });

        radioBtnXBOX.setText("XBOX");

        radioBtnNintendo.setText("Nintendo");

        javax.swing.GroupLayout panelPlataformaLayout = new javax.swing.GroupLayout(panelPlataforma);
        panelPlataforma.setLayout(panelPlataformaLayout);
        panelPlataformaLayout.setHorizontalGroup(
            panelPlataformaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPlataformaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPlataformaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioBtnPS)
                    .addComponent(radioBtnXBOX)
                    .addComponent(radioBtnNintendo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPlataformaLayout.setVerticalGroup(
            panelPlataformaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPlataformaLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(radioBtnPS)
                .addGap(18, 18, 18)
                .addComponent(radioBtnXBOX)
                .addGap(18, 18, 18)
                .addComponent(radioBtnNintendo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelDate.setBackground(new java.awt.Color(204, 153, 255));
        panelDate.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Release Date", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        panelDate.setForeground(new java.awt.Color(0, 0, 0));

        radioBtnMinDate.setText("MinDate");

        radioBtnMaxDate.setText("MaxDate");

        javax.swing.GroupLayout panelDateLayout = new javax.swing.GroupLayout(panelDate);
        panelDate.setLayout(panelDateLayout);
        panelDateLayout.setHorizontalGroup(
            panelDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioBtnMaxDate)
                    .addComponent(radioBtnMinDate))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDateLayout.setVerticalGroup(
            panelDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDateLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(radioBtnMinDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioBtnMaxDate)
                .addGap(11, 11, 11))
        );

        panelScore.setBackground(new java.awt.Color(204, 153, 255));
        panelScore.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Score", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        panelScore.setForeground(new java.awt.Color(0, 0, 0));

        radioBtnMaxScore.setText("MaxScore");

        radioBtnMinScore.setText("MinScore");

        javax.swing.GroupLayout panelScoreLayout = new javax.swing.GroupLayout(panelScore);
        panelScore.setLayout(panelScoreLayout);
        panelScoreLayout.setHorizontalGroup(
            panelScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelScoreLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioBtnMinScore)
                    .addComponent(radioBtnMaxScore))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelScoreLayout.setVerticalGroup(
            panelScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelScoreLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(radioBtnMinScore)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioBtnMaxScore)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("VIDEOJUEGOS");

        btnFiltrar.setText("Filtrar");

        btnQuitarFiltros.setText("Quitar Filtros");

        TotalGamesList.setBackground(new java.awt.Color(153, 153, 153));
        TotalGamesList.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        TotalGamesList.setForeground(new java.awt.Color(255, 255, 255));
        TotalGamesList.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                TotalGamesListAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane3.setViewportView(TotalGamesList);

        btnFirstPage.setText("<<");
        btnFirstPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstPageActionPerformed(evt);
            }
        });

        btnPageBefore.setText("<");
        btnPageBefore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPageBeforeActionPerformed(evt);
            }
        });

        btnLastPage.setText(">>");
        btnLastPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastPageActionPerformed(evt);
            }
        });

        btnNextPage.setText(">");
        btnNextPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextPageActionPerformed(evt);
            }
        });

        labelNumPage.setForeground(new java.awt.Color(0, 0, 0));
        labelNumPage.setText("0/0");

        javax.swing.GroupLayout PanelVideojuegosLayout = new javax.swing.GroupLayout(PanelVideojuegos);
        PanelVideojuegos.setLayout(PanelVideojuegosLayout);
        PanelVideojuegosLayout.setHorizontalGroup(
            PanelVideojuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVideojuegosLayout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelICONSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
            .addGroup(PanelVideojuegosLayout.createSequentialGroup()
                .addGroup(PanelVideojuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelVideojuegosLayout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(jLabel12))
                    .addGroup(PanelVideojuegosLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(labelFiltros)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelVideojuegosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelVideojuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnQuitarFiltros, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(panelPlataforma, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelScore, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFiltrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelVideojuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelVideojuegosLayout.createSequentialGroup()
                        .addComponent(btnFirstPage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPageBefore)
                        .addGap(280, 280, 280)
                        .addComponent(labelNumPage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNextPage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLastPage))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );
        PanelVideojuegosLayout.setVerticalGroup(
            PanelVideojuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVideojuegosLayout.createSequentialGroup()
                .addGroup(PanelVideojuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelVideojuegosLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelVideojuegosLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(panelICONSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addComponent(labelFiltros)
                .addGap(18, 18, 18)
                .addGroup(PanelVideojuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelVideojuegosLayout.createSequentialGroup()
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelPlataforma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFiltrar)
                        .addGap(18, 18, 18)
                        .addComponent(btnQuitarFiltros)
                        .addGap(0, 67, Short.MAX_VALUE))
                    .addGroup(PanelVideojuegosLayout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addGap(18, 18, 18)
                        .addGroup(PanelVideojuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnFirstPage)
                            .addComponent(btnPageBefore)
                            .addComponent(btnLastPage)
                            .addComponent(btnNextPage)
                            .addComponent(labelNumPage))
                        .addGap(18, 18, 18))))
        );

        PanelVentana.add(PanelVideojuegos, "card3");

        PanelMenuAdmin.setBackground(new java.awt.Color(0, 0, 102));
        PanelMenuAdmin.setForeground(new java.awt.Color(255, 255, 255));
        PanelMenuAdmin.setPreferredSize(new java.awt.Dimension(850, 800));
        PanelMenuAdmin.setLayout(null);

        btnAltaVideojuegos.setBackground(new java.awt.Color(0, 0, 0));
        btnAltaVideojuegos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAltaVideojuegos.setForeground(new java.awt.Color(255, 255, 255));
        btnAltaVideojuegos.setText("Alta Videojuegos");
        btnAltaVideojuegos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaVideojuegosActionPerformed(evt);
            }
        });
        PanelMenuAdmin.add(btnAltaVideojuegos);
        btnAltaVideojuegos.setBounds(110, 650, 226, 49);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\CARLA LLENAS\\OneDrive\\Documentos\\NetBeansProjects\\LudoxCliente\\src\\main\\images\\icons8-games-folder-100.png")); // NOI18N
        PanelMenuAdmin.add(jLabel9);
        jLabel9.setBounds(180, 420, 120, 193);

        btnUsuarios.setBackground(new java.awt.Color(0, 0, 0));
        btnUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuarios.setText("Usuarios");
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        PanelMenuAdmin.add(btnUsuarios);
        btnUsuarios.setBounds(120, 240, 226, 49);

        btnEditVideojuegos.setBackground(new java.awt.Color(0, 0, 0));
        btnEditVideojuegos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEditVideojuegos.setForeground(new java.awt.Color(255, 255, 255));
        btnEditVideojuegos.setText("Editar Videojuegos");
        btnEditVideojuegos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditVideojuegosActionPerformed(evt);
            }
        });
        PanelMenuAdmin.add(btnEditVideojuegos);
        btnEditVideojuegos.setBounds(500, 650, 226, 49);

        btnPermisos.setBackground(new java.awt.Color(0, 0, 0));
        btnPermisos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPermisos.setForeground(new java.awt.Color(255, 255, 255));
        btnPermisos.setText("Permisos");
        btnPermisos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPermisosActionPerformed(evt);
            }
        });
        PanelMenuAdmin.add(btnPermisos);
        btnPermisos.setBounds(480, 240, 226, 49);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\CARLA LLENAS\\OneDrive\\Documentos\\NetBeansProjects\\LudoxCliente\\src\\main\\images\\icons8-llamada-de-conferencia-100.png")); // NOI18N
        PanelMenuAdmin.add(jLabel7);
        jLabel7.setBounds(180, 40, 120, 190);
        PanelMenuAdmin.add(jSeparator4);
        jSeparator4.setBounds(80, 360, 659, 10);

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\CARLA LLENAS\\OneDrive\\Documentos\\NetBeansProjects\\LudoxCliente\\src\\main\\images\\icons8-editar-propiedad-100 (1).png")); // NOI18N
        PanelMenuAdmin.add(jLabel11);
        jLabel11.setBounds(560, 450, 110, 130);

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\CARLA LLENAS\\OneDrive\\Documentos\\NetBeansProjects\\LudoxCliente\\src\\main\\images\\icons8-user-100.png")); // NOI18N
        PanelMenuAdmin.add(jLabel13);
        jLabel13.setBounds(550, 60, 100, 160);

        labelFondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\CARLA LLENAS\\OneDrive\\Documentos\\NetBeansProjects\\LudoxCliente\\src\\main\\images\\fondoMenuAdmin.jpg")); // NOI18N
        labelFondo.setMaximumSize(new java.awt.Dimension(850, 800));
        labelFondo.setMinimumSize(new java.awt.Dimension(850, 800));
        labelFondo.setPreferredSize(new java.awt.Dimension(840, 800));
        PanelMenuAdmin.add(labelFondo);
        labelFondo.setBounds(0, 0, 850, 800);

        PanelVentana.add(PanelMenuAdmin, "card5");

        PanelAjustes.setBackground(new java.awt.Color(204, 204, 255));
        PanelAjustes.setLayout(null);

        labelNombreApell.setForeground(new java.awt.Color(255, 255, 255));
        labelNombreApell.setText("Nombre y Apellidos");
        PanelAjustes.add(labelNombreApell);
        labelNombreApell.setBounds(39, 108, 107, 16);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Correo electrónico");
        PanelAjustes.add(jLabel3);
        jLabel3.setBounds(39, 195, 101, 16);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Constraseña");
        PanelAjustes.add(jLabel5);
        jLabel5.setBounds(42, 282, 72, 16);

        btnSave.setText("GUARDAR");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        PanelAjustes.add(btnSave);
        btnSave.setBounds(583, 178, 125, 50);

        txtNameEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameEditActionPerformed(evt);
            }
        });
        PanelAjustes.add(txtNameEdit);
        txtNameEdit.setBounds(200, 100, 274, 32);
        PanelAjustes.add(txtMailEdit);
        txtMailEdit.setBounds(200, 187, 274, 32);
        PanelAjustes.add(txtPassEdit);
        txtPassEdit.setBounds(200, 274, 274, 32);

        btnLogout.setText("LOG OUT");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        PanelAjustes.add(btnLogout);
        btnLogout.setBounds(693, 721, 96, 45);

        btnSalir.setText("Salir del programa");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        PanelAjustes.add(btnSalir);
        btnSalir.setBounds(60, 721, 114, 45);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("MODIFICAR DATOS");
        PanelAjustes.add(jLabel8);
        jLabel8.setBounds(39, 26, 159, 25);

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        PanelAjustes.add(jSeparator2);
        jSeparator2.setBounds(39, 69, 623, 10);

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        PanelAjustes.add(jSeparator3);
        jSeparator3.setBounds(42, 383, 635, 10);

        labelFondoo1.setForeground(new java.awt.Color(0, 0, 0));
        labelFondoo1.setIcon(new javax.swing.ImageIcon("C:\\Users\\CARLA LLENAS\\OneDrive\\Documentos\\NetBeansProjects\\LudoxCliente\\src\\main\\images\\fondoprincipalbueno.png")); // NOI18N
        PanelAjustes.add(labelFondoo1);
        labelFondoo1.setBounds(1, -1, 850, 800);

        PanelVentana.add(PanelAjustes, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(PanelVentana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelVentana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * event del botó Admin per obrir el frame de menu admin
     */
    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        // TODO add your handling code here:
        PanelVentana.removeAll();
        PanelVentana.add(PanelMenuAdmin);
        PanelVentana.repaint();
        PanelVentana.revalidate();
    }//GEN-LAST:event_btnAdminActionPerformed

    private void labelReseñasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_labelReseñasKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_labelReseñasKeyPressed

    private void panelAjustesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAjustesMouseClicked
        // TODO add your handling code here:
        PanelVentana.removeAll();
        PanelVentana.add(PanelAjustes);
        PanelVentana.repaint();
        PanelVentana.revalidate();
    }//GEN-LAST:event_panelAjustesMouseClicked

    private void panelVideojuegosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelVideojuegosMouseClicked
        // TODO add your handling code here:
        PanelVentana.removeAll();
        PanelVentana.add(PanelVideojuegos);
        PanelVentana.repaint();
        PanelVentana.revalidate();

        //QueryFilter qf = new QueryFilter(null, null, 0, 0, null, null, null, null, null);
//        getGamesLst(qf, ActualPage);
        getPageNumber();

    }//GEN-LAST:event_panelVideojuegosMouseClicked

    private void labelVideojuegosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelVideojuegosMouseClicked
        // TODO add your handling code here:
//        PanelVentana.removeAll();
//        PanelVentana.add(PanelVideojuegos);
//        PanelVentana.repaint();
//        PanelVentana.revalidate();
    }//GEN-LAST:event_labelVideojuegosMouseClicked

    private void txtNameEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameEditActionPerformed

    private void labelAjustesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAjustesMouseClicked
        // TODO add your handling code here:
        PanelVentana.removeAll();
        PanelVentana.add(PanelAjustes);
        PanelVentana.repaint();
        PanelVentana.revalidate();
    }//GEN-LAST:event_labelAjustesMouseClicked

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new login().setVisible(true);

    }//GEN-LAST:event_btnLogoutActionPerformed
    /**
     * event del botó del panel del menu admin que ens obrirà el frame de menu
     * de permisos d'usuari
     */
    private void btnPermisosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPermisosActionPerformed
        // TODO add your handling code here:
        new Permisos().setVisible(true);
    }//GEN-LAST:event_btnPermisosActionPerformed

    /**
     * event del botó del panel del menu admin que ens obrirà el frame d'alta de
     * videojocs
     */
    private void btnAltaVideojuegosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaVideojuegosActionPerformed
        // TODO add your handling code here:
        new AltaVideojuegos().setVisible(true);;
    }//GEN-LAST:event_btnAltaVideojuegosActionPerformed
    /**
     * event del botó del panel del menu admin que ens obrirà el frame d'edició
     * de videojocs
     */
    private void btnEditVideojuegosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditVideojuegosActionPerformed
        // TODO add your handling code here:
        new EditarVideojuegos().setVisible(true);
    }//GEN-LAST:event_btnEditVideojuegosActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        // TODO add your handling code here:
        new ControlUsuarios().setVisible(true);
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void labelTittleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelTittleMouseClicked
        // TODO add your handling code here:
        PanelVentana.removeAll();
        PanelVentana.add(PanelPrincipal);
        PanelVentana.repaint();
        PanelVentana.revalidate();
    }//GEN-LAST:event_labelTittleMouseClicked

    /**
     * metode de moment inactiu per sistema de filtres
     */
    private void radioBtnPSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnPSActionPerformed
        // TODO add your handling code here: 
        try {
            ClientConnection.getDos().writeByte(2);
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (radioBtnPS.isSelected()) {
            //QueryFilter qf = new QueryFilter("PlayStation", null, 0, 0, null, null, null, null, null);
        }
    }//GEN-LAST:event_radioBtnPSActionPerformed

    private void TotalGamesListAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TotalGamesListAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalGamesListAncestorAdded
    /**
     * event del botó del panel de editar dades d'usuari que ens guardara els
     * canvis fets
     */
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            // TODO add your handling code here:
            ClientConnection.getDos().writeByte(4);
            EditUser eu = new EditUser();

            eu.setUsername(ClientHelper.username);
            if (!txtNameEdit.getText().trim().equals("")) {
                eu.setName(txtNameEdit.getText());
            }
            if (!txtMailEdit.getText().trim().equals("")) {
                eu.setMail(txtMailEdit.getText());
            }
            if (!txtPassEdit.getText().trim().equals("")) {
                eu.setPassword(Encrypter.getEncodedString(txtPassEdit.getText()));
            }
            ClientConnection.getOos().writeObject(eu);
            boolean correct = ClientConnection.getDis().readBoolean();

            if (correct) {
                if (!txtNameEdit.getText().trim().equals("")) {
                    user.setName(txtNameEdit.getText());
                }
                if (!txtMailEdit.getText().trim().equals("")) {
                    user.setMail(txtMailEdit.getText());
                }
                JOptionPane.showMessageDialog(this, "Se han guardado los cambios correctamente");
            }
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Error al guardar los cambios");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * acció del botó per anar a la primera pagina
     */
    private void btnFirstPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstPageActionPerformed
        // TODO add your handling code here:
        ActualPage = 1;
//        QueryFilter qf = new QueryFilter(null, null, 0, 0, null, null, null, null, null);
        //  getGamesLst(qf, ActualPage);
        getPageNumber();
    }//GEN-LAST:event_btnFirstPageActionPerformed

    private void btnLastPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastPageActionPerformed
        // TODO add your handling code here:
        ActualPage = totalPaginas;
        // QueryFilter qf = new QueryFilter(null, null, 0, 0, null, null, null, null, null);
        // getGamesLst(qf, ActualPage);
        getPageNumber();
    }//GEN-LAST:event_btnLastPageActionPerformed
    /**
     * acció del botó per retrocedir de pagina
     */
    private void btnPageBeforeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPageBeforeActionPerformed
        // TODO add your handling code here:
        if (ActualPage > 1) {
            ActualPage--;
            // QueryFilter qf = new QueryFilter(null, null, 0, 0, null, null, null, null, null);
            //   getGamesLst(qf, ActualPage);
            getPageNumber();
        }
    }//GEN-LAST:event_btnPageBeforeActionPerformed

    /**
     * acció del botó per anar a la seguent pagina
     */
    private void btnNextPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextPageActionPerformed
        // TODO add your handling code here:
        if (ActualPage < totalPaginas) {
            ActualPage++;
//            QueryFilter qf = new QueryFilter(null, null, 0, 0, null, null, null, null, null);
            //          getGamesLst(qf, ActualPage);
            getPageNumber();
        }
    }//GEN-LAST:event_btnNextPageActionPerformed

    private void GamesListAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_GamesListAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_GamesListAncestorAdded

    private void btnDERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDERActionPerformed
        // TODO add your handling code here:
        if (contador == 4) {
            contador = 0;
        }
        contador++;
        carruselLabel.setIcon(img[contador]);
    }//GEN-LAST:event_btnDERActionPerformed

    private void btnIZQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIZQActionPerformed
        // TODO add your handling code here:
        if (contador == 1) {
            contador = 4;
        }
        contador--;
        carruselLabel.setIcon(img[contador]);
    }//GEN-LAST:event_btnIZQActionPerformed

    private void btnAUTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAUTOActionPerformed
        // TODO add your handling code here:
        Timer timer  = new Timer(600, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                carruselLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrusel/" + contador + ".png")));
                contador++;
                if(contador==4)contador=1;
            }
        });
        timer.start();
    }//GEN-LAST:event_btnAUTOActionPerformed
    /**
     * metode que envia al servidor un byte perque ens torni un llistat dels
     * noms dels videojocs actuals de la base de dades amb la puntució més alta,
     * emplena el scrollPane
     */
    public void getTop5() throws IOException, ClassNotFoundException {

        DefaultListModel<String> model = new DefaultListModel<>();

        GamesList.setModel(model);

        String[] gameNames = ClientHelper.listVideogamesTop5.stream().map(v -> v.getName()).toArray(size -> new String[size]);

        for (int i = 0; i < gameNames.length; i++) {
            model.addElement(gameNames[i]);
        }
    }

    /**
     * metode que envia al servidor un byte perque ens torni un llistat dels
     * noms dels videojocs actuals de la base de dades Amb el llistat, emplena
     * el scrollPane
     */
    public void getGamesLst(QueryFilter qf, int paginaActual) {

        try {
            ClientConnection.getDos().writeByte(2);
            ClientConnection.getOos().writeObject(qf);
            totalPaginas = ClientConnection.getDis().readByte();
            ClientConnection.getDos().writeInt(paginaActual);
            List<Videogame> gameList = (List<Videogame>) ClientConnection.getOis().readObject();

            DefaultListModel<String> model = new DefaultListModel<>();

            TotalGamesList.setModel(model);

            String[] gameNames = gameList.stream().map(v -> v.getName()).toArray(size -> new String[size]);

            for (int i = 0; i < gameNames.length; i++) {
                model.addElement(gameNames[i]);
            }

        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * metode per escriure al label el numero de pagina actual que es visualitza
     */
    public void getPageNumber() {

        labelNumPage.setText(ActualPage + "/" + totalPaginas);
    }
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> GamesList;
    private javax.swing.JPanel PanelAjustes;
    private javax.swing.JPanel PanelMenuAdmin;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JPanel PanelVentana;
    private javax.swing.JPanel PanelVideojuegos;
    private javax.swing.JList<String> TotalGamesList;
    private javax.swing.JButton btnAUTO;
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnAltaVideojuegos;
    private javax.swing.JButton btnDER;
    private javax.swing.JButton btnEditVideojuegos;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnFirstPage;
    private javax.swing.JButton btnIZQ;
    private javax.swing.JButton btnLastPage;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnNextPage;
    private javax.swing.JButton btnPageBefore;
    private javax.swing.JButton btnPermisos;
    private javax.swing.JButton btnQuitarFiltros;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JLabel carruselLabel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel labelAjustes;
    private javax.swing.JLabel labelFiltros;
    private javax.swing.JLabel labelFondo;
    private javax.swing.JLabel labelFondoo;
    private javax.swing.JLabel labelFondoo1;
    private javax.swing.JLabel labelNombreApell;
    private javax.swing.JLabel labelNumPage;
    private javax.swing.JLabel labelReseñas;
    private javax.swing.JLabel labelTittle;
    private javax.swing.JLabel labelVideojuegos;
    private javax.swing.JLabel logoAjustes;
    private javax.swing.JLabel logoAlquiler;
    private javax.swing.JLabel logoJuegos;
    private javax.swing.JLabel logoReseñas;
    private javax.swing.JPanel panelAjustes;
    private javax.swing.JPanel panelAlquiler;
    private javax.swing.JPanel panelDate;
    private javax.swing.JPanel panelICONSearch;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelPlataforma;
    private javax.swing.JPanel panelReseñas;
    private javax.swing.JPanel panelScore;
    private javax.swing.JPanel panelTittle;
    private javax.swing.JPanel panelVideojuegos;
    private javax.swing.JRadioButton radioBtnMaxDate;
    private javax.swing.JRadioButton radioBtnMaxScore;
    private javax.swing.JRadioButton radioBtnMinDate;
    private javax.swing.JRadioButton radioBtnMinScore;
    private javax.swing.JRadioButton radioBtnNintendo;
    private javax.swing.JRadioButton radioBtnPS;
    private javax.swing.JRadioButton radioBtnXBOX;
    private javax.swing.JTextField txtMailEdit;
    private javax.swing.JTextField txtNameEdit;
    private javax.swing.JTextField txtPassEdit;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

}
