package forms;

import data.Category;
import data.ClientConnection;
import helpers.EditUser;
import data.ClientHelper;
import data.Platforms;
import data.Rental;
import helpers.QueryFilter;
import data.User;
import data.Videogame;
import encrypt.Encrypter;
import forms.admin.AltaVideojuegos;
import forms.admin.ControlUsuarios;
import forms.admin.EditarVideojuegos;
import forms.admin.Permisos;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author CARLA LLENAS
 */


public class Principal extends javax.swing.JFrame {

    private static Videogame videogames;
    Rental rental;
    private static int totalPaginas;
    private static int ActualPage = 1;
    private static String FiltroPlat;
    private static String FiltroCat;
    private static double FiltroScore;
    private static String FiltroDate;
    private static QueryFilter qf;
    private static QueryFilter qfOld;
    private static String FiltroName;

    login log = new login();
    User user;
    registro reg;
    Permisos per = new Permisos();

    //CANTIDAD IMAGENES + 1
    ImageIcon img[] = new ImageIcon[ClientHelper.listVideogamesTop5.size() + 1];
    int contador = 1;

    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * constructor de la classe. verificarà també si l'usuari entrat es admin o
     * no
     *
     * @param log paramentre d'objecte de la clase login
     * @param user paramentre de l'usuari de la clase User
     */
    public Principal(login log, User user) {
        initComponents();
        try {
            getTop5();
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setLocationRelativeTo(null);
        this.log = log;
        this.user = user;

        if (!user.isIsAdmin()) {
            btnAdmin.setVisible(false);
        }

        if (ClientHelper.listVideogamesTop5.size() > 0) {
            for (int i = 1; i < ClientHelper.listVideogamesTop5.size() + 1; i++) {
                img[i] = new ImageIcon(new ImageIcon(ClientHelper.listVideogamesTop5.get(i - 1).getGameImage()).getImage().getScaledInstance(carruselLabel.getWidth(), carruselLabel.getHeight(), Image.SCALE_DEFAULT));
            }
            carruselLabel.setIcon(img[1]);
        }

        String[] Plat = new String[ClientHelper.listPlataformas.size()];
        int[] i = {0};
        ClientHelper.listPlataformas.forEach(p -> {
            Plat[i[0]] = p.getName();
            i[0]++;
        });

        String[] Cat = new String[ClientHelper.listCategory.size()];
        i[0] = 0;
        ClientHelper.listCategory.forEach(c -> {
            Cat[i[0]] = c.getCategory();
            i[0]++;
        });

        ComboPlatforms.setModel(new DefaultComboBoxModel<>(Plat));

        ComboCategory.setModel(new DefaultComboBoxModel<>(Cat));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        panelTittle = new javax.swing.JPanel();
        labelTittle = new javax.swing.JLabel();
        panelAlquiler = new javax.swing.JPanel();
        logoAlquiler = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panelVideojuegos = new javax.swing.JPanel();
        logoJuegos = new javax.swing.JLabel();
        labelVideojuegos = new javax.swing.JLabel();
        panelAjustes = new javax.swing.JPanel();
        logoAjustes = new javax.swing.JLabel();
        labelAjustes = new javax.swing.JLabel();
        panelReseñas = new javax.swing.JPanel();
        logoReseñas = new javax.swing.JLabel();
        labelReseñas = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnAdmin = new javax.swing.JButton();
        PanelVentana = new javax.swing.JPanel();
        PanelPrincipal = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        GamesList = new javax.swing.JList<>();
        carruselLabel = new javax.swing.JLabel();
        btnIZQ = new javax.swing.JButton();
        btnAUTO = new javax.swing.JButton();
        btnDER = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        labelFondoo = new javax.swing.JLabel();
        PanelVideojuegos = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        labelFiltros = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        btnFiltrar = new javax.swing.JButton();
        btnQuitarFiltros = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TotalGamesList = new javax.swing.JList<>();
        btnFirstPage = new javax.swing.JButton();
        btnPageBefore = new javax.swing.JButton();
        btnLastPage = new javax.swing.JButton();
        btnNextPage = new javax.swing.JButton();
        labelNumPage = new javax.swing.JLabel();
        btnSearchGame = new javax.swing.JButton();
        labelPlatform1 = new javax.swing.JLabel();
        ComboPlatforms = new javax.swing.JComboBox<>();
        labelPlatform2 = new javax.swing.JLabel();
        labelPlatform3 = new javax.swing.JLabel();
        labelPlatform4 = new javax.swing.JLabel();
        ComboCategory = new javax.swing.JComboBox<>();
        txtReleaseDate = new javax.swing.JTextField();
        txtScore = new javax.swing.JTextField();
        PanelMenuAdmin = new javax.swing.JPanel();
        btnAltaVideojuegos = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnUsuarios = new javax.swing.JButton();
        btnEditVideojuegos = new javax.swing.JButton();
        btnPermisos = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        labelFondo = new javax.swing.JLabel();
        PanelAjustes = new javax.swing.JPanel();
        labelNombreApell = new javax.swing.JLabel();
        labelCorreo = new javax.swing.JLabel();
        labelPass = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        txtNameEdit = new javax.swing.JTextField();
        txtMailEdit = new javax.swing.JTextField();
        txtPassEdit = new javax.swing.JTextField();
        btnLogout = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        labelFondoo1 = new javax.swing.JLabel();
        PanelAlquileres = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        labelCat = new javax.swing.JLabel();
        labelCat1 = new javax.swing.JLabel();
        LabelGameName = new javax.swing.JLabel();
        labelFechaFIN = new javax.swing.JLabel();
        labelFechaINICIO = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelCat2 = new javax.swing.JLabel();
        labelCat3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        labelCat4 = new javax.swing.JLabel();
        labelCat5 = new javax.swing.JLabel();
        LabelGameName2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        labelCat6 = new javax.swing.JLabel();
        labelCat7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        labelCat8 = new javax.swing.JLabel();
        labelCat9 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        labelCat10 = new javax.swing.JLabel();
        labelCat11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ludox Menu");
        setBackground(new java.awt.Color(0, 0, 0));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.black);
        setLocationByPlatform(true);
        setUndecorated(true);

        panelMenu.setBackground(new java.awt.Color(0, 0, 0));

        panelTittle.setBackground(new java.awt.Color(0, 0, 0));

        labelTittle.setBackground(new java.awt.Color(0, 0, 0));
        labelTittle.setFont(new java.awt.Font("Liberation Sans Narrow", 0, 48)); // NOI18N
        labelTittle.setForeground(new java.awt.Color(255, 255, 255));
        labelTittle.setText("Ludox");
        labelTittle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelTittle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelTittleMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelTittleLayout = new javax.swing.GroupLayout(panelTittle);
        panelTittle.setLayout(panelTittleLayout);
        panelTittleLayout.setHorizontalGroup(
            panelTittleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTittleLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(labelTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );
        panelTittleLayout.setVerticalGroup(
            panelTittleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTittleLayout.createSequentialGroup()
                .addGap(0, 38, Short.MAX_VALUE)
                .addComponent(labelTittle))
        );

        panelAlquiler.setBackground(new java.awt.Color(102, 102, 255));

        logoAlquiler.setIcon(new javax.swing.ImageIcon("C:\\Users\\CARLA LLENAS\\OneDrive\\Documentos\\NetBeansProjects\\LudoxCliente\\src\\main\\images\\icons8-carrito-de-la-compra-cargado-48.png")); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Alquileres");

        javax.swing.GroupLayout panelAlquilerLayout = new javax.swing.GroupLayout(panelAlquiler);
        panelAlquiler.setLayout(panelAlquilerLayout);
        panelAlquilerLayout.setHorizontalGroup(
            panelAlquilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlquilerLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(logoAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAlquilerLayout.setVerticalGroup(
            panelAlquilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoAlquiler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelAlquilerLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        panelVideojuegos.setBackground(new java.awt.Color(102, 0, 204));
        panelVideojuegos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelVideojuegosMouseClicked(evt);
            }
        });

        logoJuegos.setIcon(new javax.swing.ImageIcon("C:\\Users\\CARLA LLENAS\\OneDrive\\Documentos\\NetBeansProjects\\LudoxCliente\\src\\main\\images\\icons8-battle-64.png")); // NOI18N

        labelVideojuegos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelVideojuegos.setForeground(new java.awt.Color(0, 0, 0));
        labelVideojuegos.setText("Videojuegos");
        labelVideojuegos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelVideojuegosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelVideojuegosLayout = new javax.swing.GroupLayout(panelVideojuegos);
        panelVideojuegos.setLayout(panelVideojuegosLayout);
        panelVideojuegosLayout.setHorizontalGroup(
            panelVideojuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVideojuegosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoJuegos)
                .addGap(38, 38, 38)
                .addComponent(labelVideojuegos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelVideojuegosLayout.setVerticalGroup(
            panelVideojuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoJuegos)
            .addGroup(panelVideojuegosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(labelVideojuegos))
        );

        panelAjustes.setBackground(new java.awt.Color(102, 102, 255));
        panelAjustes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelAjustesMouseClicked(evt);
            }
        });

        logoAjustes.setIcon(new javax.swing.ImageIcon("C:\\Users\\CARLA LLENAS\\OneDrive\\Documentos\\NetBeansProjects\\LudoxCliente\\src\\main\\images\\icons8-engranajes-50.png")); // NOI18N

        labelAjustes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelAjustes.setForeground(new java.awt.Color(0, 0, 0));
        labelAjustes.setText("Ajustes");
        labelAjustes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAjustesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelAjustesLayout = new javax.swing.GroupLayout(panelAjustes);
        panelAjustes.setLayout(panelAjustesLayout);
        panelAjustesLayout.setHorizontalGroup(
            panelAjustesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAjustesLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(logoAjustes, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelAjustes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAjustesLayout.setVerticalGroup(
            panelAjustesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAjustesLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(labelAjustes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(logoAjustes, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
        );

        panelReseñas.setBackground(new java.awt.Color(102, 0, 204));

        logoReseñas.setIcon(new javax.swing.ImageIcon("C:\\Users\\CARLA LLENAS\\OneDrive\\Documentos\\NetBeansProjects\\LudoxCliente\\src\\main\\images\\icons8-mano-con-pluma-50.png")); // NOI18N

        labelReseñas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelReseñas.setForeground(new java.awt.Color(0, 0, 0));
        labelReseñas.setText("Mis reseñas");
        labelReseñas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                labelReseñasKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panelReseñasLayout = new javax.swing.GroupLayout(panelReseñas);
        panelReseñas.setLayout(panelReseñasLayout);
        panelReseñasLayout.setHorizontalGroup(
            panelReseñasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReseñasLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(logoReseñas, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(labelReseñas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelReseñasLayout.setVerticalGroup(
            panelReseñasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoReseñas, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
            .addGroup(panelReseñasLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(labelReseñas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSeparator1.setForeground(new java.awt.Color(102, 0, 204));
        jSeparator1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        btnAdmin.setBackground(new java.awt.Color(0, 0, 153));
        btnAdmin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnAdmin.setText("ADMINISTRADOR");
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTittle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(btnAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelAjustes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelReseñas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelAlquiler, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelVideojuegos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(panelTittle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(panelVideojuegos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(panelAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(panelReseñas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(panelAjustes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(226, 226, 226)
                .addComponent(btnAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PanelVentana.setBackground(new java.awt.Color(255, 255, 255));
        PanelVentana.setLayout(new java.awt.CardLayout());

        PanelPrincipal.setBackground(new java.awt.Color(204, 204, 204));
        PanelPrincipal.setPreferredSize(new java.awt.Dimension(840, 800));
        PanelPrincipal.setLayout(null);

        GamesList.setBackground(new java.awt.Color(102, 102, 255));
        GamesList.setFont(new java.awt.Font("Source Sans Pro Light", 2, 18)); // NOI18N
        GamesList.setForeground(new java.awt.Color(0, 0, 0));
        GamesList.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                GamesListAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane2.setViewportView(GamesList);

        PanelPrincipal.add(jScrollPane2);
        jScrollPane2.setBounds(580, 100, 226, 240);

        carruselLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelPrincipal.add(carruselLabel);
        carruselLabel.setBounds(39, 40, 500, 690);

        btnIZQ.setText("Anterior");
        btnIZQ.setToolTipText("");
        btnIZQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIZQActionPerformed(evt);
            }
        });
        PanelPrincipal.add(btnIZQ);
        btnIZQ.setBounds(39, 748, 80, 24);

        btnAUTO.setText("Reproduccion Automatica");
        btnAUTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAUTOActionPerformed(evt);
            }
        });
        PanelPrincipal.add(btnAUTO);
        btnAUTO.setBounds(220, 750, 160, 24);

        btnDER.setText("Siguiente");
        btnDER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDERActionPerformed(evt);
            }
        });
        PanelPrincipal.add(btnDER);
        btnDER.setBounds(450, 750, 100, 24);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("NUEVOS AÑADIDOS");
        PanelPrincipal.add(jLabel10);
        jLabel10.setBounds(590, 480, 230, 50);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("TOP 5 VIDEOJUEGOS");
        PanelPrincipal.add(jLabel14);
        jLabel14.setBounds(580, 50, 230, 50);

        labelFondoo.setForeground(new java.awt.Color(0, 0, 0));
        labelFondoo.setIcon(new javax.swing.ImageIcon("C:\\Users\\CARLA LLENAS\\OneDrive\\Documentos\\NetBeansProjects\\LudoxCliente\\src\\main\\images\\fondoprincipalbueno.png")); // NOI18N
        PanelPrincipal.add(labelFondoo);
        labelFondoo.setBounds(1, -1, 850, 800);

        PanelVentana.add(PanelPrincipal, "card4");

        PanelVideojuegos.setBackground(new java.awt.Color(204, 153, 255));

        labelFiltros.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelFiltros.setForeground(new java.awt.Color(255, 255, 255));
        labelFiltros.setText("FILTROS");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("VIDEOJUEGOS");

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));

        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        btnQuitarFiltros.setText("Quitar Filtros");

        TotalGamesList.setBackground(new java.awt.Color(153, 153, 153));
        TotalGamesList.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        TotalGamesList.setForeground(new java.awt.Color(0, 0, 0));
        TotalGamesList.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                TotalGamesListAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        TotalGamesList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TotalGamesListMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TotalGamesList);

        btnFirstPage.setText("<<");
        btnFirstPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstPageActionPerformed(evt);
            }
        });

        btnPageBefore.setText("<");
        btnPageBefore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPageBeforeActionPerformed(evt);
            }
        });

        btnLastPage.setText(">>");
        btnLastPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastPageActionPerformed(evt);
            }
        });

        btnNextPage.setText(">");
        btnNextPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextPageActionPerformed(evt);
            }
        });

        labelNumPage.setForeground(new java.awt.Color(255, 255, 255));
        labelNumPage.setText("0/0");

        btnSearchGame.setIcon(new javax.swing.ImageIcon("C:\\Users\\CARLA LLENAS\\OneDrive\\Documentos\\NetBeansProjects\\LudoxCliente\\src\\main\\images\\icons8-búsqueda-64.png")); // NOI18N
        btnSearchGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchGameActionPerformed(evt);
            }
        });

        labelPlatform1.setForeground(new java.awt.Color(255, 255, 255));
        labelPlatform1.setText("Plataforma");

        labelPlatform2.setForeground(new java.awt.Color(255, 255, 255));
        labelPlatform2.setText("Puntuación");

        labelPlatform3.setForeground(new java.awt.Color(255, 255, 255));
        labelPlatform3.setText("Categoria");

        labelPlatform4.setForeground(new java.awt.Color(255, 255, 255));
        labelPlatform4.setText("Fecha de lanzamiento");

        javax.swing.GroupLayout PanelVideojuegosLayout = new javax.swing.GroupLayout(PanelVideojuegos);
        PanelVideojuegos.setLayout(PanelVideojuegosLayout);
        PanelVideojuegosLayout.setHorizontalGroup(
            PanelVideojuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVideojuegosLayout.createSequentialGroup()
                .addGroup(PanelVideojuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelVideojuegosLayout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(jLabel12))
                    .addGroup(PanelVideojuegosLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearchGame)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelVideojuegosLayout.createSequentialGroup()
                .addGroup(PanelVideojuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelVideojuegosLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(PanelVideojuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPlatform2)
                            .addComponent(labelPlatform1)))
                    .addGroup(PanelVideojuegosLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(ComboPlatforms, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelVideojuegosLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(labelFiltros))
                    .addGroup(PanelVideojuegosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelVideojuegosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelVideojuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelVideojuegosLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(ComboCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelPlatform3)))
                    .addGroup(PanelVideojuegosLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(PanelVideojuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnFiltrar, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addComponent(btnQuitarFiltros, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addComponent(txtReleaseDate)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelVideojuegosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtScore, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(PanelVideojuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelVideojuegosLayout.createSequentialGroup()
                        .addComponent(btnFirstPage)
                        .addGap(18, 18, 18)
                        .addComponent(btnPageBefore)
                        .addGap(213, 213, 213)
                        .addComponent(labelNumPage)
                        .addGap(244, 244, 244)
                        .addComponent(btnNextPage)
                        .addGap(18, 18, 18)
                        .addComponent(btnLastPage))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
            .addGroup(PanelVideojuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelVideojuegosLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(labelPlatform4)
                    .addContainerGap(723, Short.MAX_VALUE)))
        );
        PanelVideojuegosLayout.setVerticalGroup(
            PanelVideojuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVideojuegosLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel12)
                .addGroup(PanelVideojuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelVideojuegosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelVideojuegosLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnSearchGame)))
                .addGroup(PanelVideojuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelVideojuegosLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(labelFiltros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelPlatform1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboPlatforms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelPlatform2)
                        .addGap(18, 18, 18)
                        .addComponent(txtScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(labelPlatform3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ComboCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(txtReleaseDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btnFiltrar)
                        .addGap(18, 18, 18)
                        .addComponent(btnQuitarFiltros))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelVideojuegosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelVideojuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLastPage)
                    .addComponent(btnNextPage)
                    .addComponent(labelNumPage)
                    .addComponent(btnPageBefore)
                    .addComponent(btnFirstPage))
                .addGap(49, 49, 49))
            .addGroup(PanelVideojuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelVideojuegosLayout.createSequentialGroup()
                    .addContainerGap(457, Short.MAX_VALUE)
                    .addComponent(labelPlatform4)
                    .addGap(341, 341, 341)))
        );

        PanelVentana.add(PanelVideojuegos, "card3");

        PanelMenuAdmin.setBackground(new java.awt.Color(0, 0, 102));
        PanelMenuAdmin.setForeground(new java.awt.Color(255, 255, 255));
        PanelMenuAdmin.setPreferredSize(new java.awt.Dimension(850, 800));
        PanelMenuAdmin.setLayout(null);

        btnAltaVideojuegos.setBackground(new java.awt.Color(0, 0, 0));
        btnAltaVideojuegos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAltaVideojuegos.setForeground(new java.awt.Color(255, 255, 255));
        btnAltaVideojuegos.setText("Alta Videojuegos");
        btnAltaVideojuegos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaVideojuegosActionPerformed(evt);
            }
        });
        PanelMenuAdmin.add(btnAltaVideojuegos);
        btnAltaVideojuegos.setBounds(110, 650, 226, 49);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\CARLA LLENAS\\OneDrive\\Documentos\\NetBeansProjects\\LudoxCliente\\src\\main\\images\\icons8-games-folder-100.png")); // NOI18N
        PanelMenuAdmin.add(jLabel9);
        jLabel9.setBounds(180, 420, 120, 193);

        btnUsuarios.setBackground(new java.awt.Color(0, 0, 0));
        btnUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuarios.setText("Usuarios");
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        PanelMenuAdmin.add(btnUsuarios);
        btnUsuarios.setBounds(120, 240, 226, 49);

        btnEditVideojuegos.setBackground(new java.awt.Color(0, 0, 0));
        btnEditVideojuegos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEditVideojuegos.setForeground(new java.awt.Color(255, 255, 255));
        btnEditVideojuegos.setText("Editar Videojuegos");
        btnEditVideojuegos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditVideojuegosActionPerformed(evt);
            }
        });
        PanelMenuAdmin.add(btnEditVideojuegos);
        btnEditVideojuegos.setBounds(500, 650, 226, 49);

        btnPermisos.setBackground(new java.awt.Color(0, 0, 0));
        btnPermisos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPermisos.setForeground(new java.awt.Color(255, 255, 255));
        btnPermisos.setText("Permisos");
        btnPermisos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPermisosActionPerformed(evt);
            }
        });
        PanelMenuAdmin.add(btnPermisos);
        btnPermisos.setBounds(480, 240, 226, 49);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\CARLA LLENAS\\OneDrive\\Documentos\\NetBeansProjects\\LudoxCliente\\src\\main\\images\\icons8-llamada-de-conferencia-100.png")); // NOI18N
        PanelMenuAdmin.add(jLabel7);
        jLabel7.setBounds(180, 40, 120, 190);
        PanelMenuAdmin.add(jSeparator4);
        jSeparator4.setBounds(80, 360, 659, 10);

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\CARLA LLENAS\\OneDrive\\Documentos\\NetBeansProjects\\LudoxCliente\\src\\main\\images\\icons8-editar-propiedad-100 (1).png")); // NOI18N
        PanelMenuAdmin.add(jLabel11);
        jLabel11.setBounds(560, 450, 110, 130);

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\CARLA LLENAS\\OneDrive\\Documentos\\NetBeansProjects\\LudoxCliente\\src\\main\\images\\icons8-user-100.png")); // NOI18N
        PanelMenuAdmin.add(jLabel13);
        jLabel13.setBounds(550, 60, 100, 160);

        labelFondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\CARLA LLENAS\\OneDrive\\Documentos\\NetBeansProjects\\LudoxCliente\\src\\main\\images\\fondoMenuAdmin.jpg")); // NOI18N
        labelFondo.setMaximumSize(new java.awt.Dimension(850, 800));
        labelFondo.setMinimumSize(new java.awt.Dimension(850, 800));
        labelFondo.setPreferredSize(new java.awt.Dimension(840, 800));
        PanelMenuAdmin.add(labelFondo);
        labelFondo.setBounds(0, 0, 850, 800);

        PanelVentana.add(PanelMenuAdmin, "card5");

        PanelAjustes.setBackground(new java.awt.Color(255, 204, 204));
        PanelAjustes.setPreferredSize(new java.awt.Dimension(850, 800));
        PanelAjustes.setLayout(null);

        labelNombreApell.setForeground(new java.awt.Color(255, 255, 255));
        labelNombreApell.setText("Nombre y Apellidos");
        PanelAjustes.add(labelNombreApell);
        labelNombreApell.setBounds(39, 108, 107, 16);

        labelCorreo.setForeground(new java.awt.Color(255, 255, 255));
        labelCorreo.setText("Correo electrónico");
        PanelAjustes.add(labelCorreo);
        labelCorreo.setBounds(39, 195, 101, 16);

        labelPass.setForeground(new java.awt.Color(255, 255, 255));
        labelPass.setText("Constraseña");
        PanelAjustes.add(labelPass);
        labelPass.setBounds(42, 282, 72, 16);

        btnSave.setText("GUARDAR");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        PanelAjustes.add(btnSave);
        btnSave.setBounds(583, 178, 125, 50);

        txtNameEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameEditActionPerformed(evt);
            }
        });
        PanelAjustes.add(txtNameEdit);
        txtNameEdit.setBounds(200, 100, 274, 32);
        PanelAjustes.add(txtMailEdit);
        txtMailEdit.setBounds(200, 187, 274, 32);
        PanelAjustes.add(txtPassEdit);
        txtPassEdit.setBounds(200, 274, 274, 32);

        btnLogout.setText("LOG OUT");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        PanelAjustes.add(btnLogout);
        btnLogout.setBounds(693, 721, 96, 45);

        btnSalir.setText("Salir del programa");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        PanelAjustes.add(btnSalir);
        btnSalir.setBounds(60, 721, 114, 45);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("MODIFICAR DATOS");
        PanelAjustes.add(jLabel8);
        jLabel8.setBounds(39, 26, 159, 25);

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        PanelAjustes.add(jSeparator2);
        jSeparator2.setBounds(39, 69, 623, 10);

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        PanelAjustes.add(jSeparator3);
        jSeparator3.setBounds(42, 383, 635, 10);

        labelFondoo1.setForeground(new java.awt.Color(0, 0, 0));
        labelFondoo1.setIcon(new javax.swing.ImageIcon("C:\\Users\\CARLA LLENAS\\OneDrive\\Documentos\\NetBeansProjects\\LudoxCliente\\src\\main\\images\\fondoprincipalbueno.png")); // NOI18N
        PanelAjustes.add(labelFondoo1);
        labelFondoo1.setBounds(1, -1, 850, 800);

        PanelVentana.add(PanelAjustes, "card2");

        PanelAlquileres.setBackground(new java.awt.Color(153, 153, 255));

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        labelCat.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        labelCat.setForeground(new java.awt.Color(255, 255, 255));
        labelCat.setText("Fecha Inicio");

        labelCat1.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        labelCat1.setForeground(new java.awt.Color(255, 255, 255));
        labelCat1.setText("Fecha Fin");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelCat, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelFechaINICIO, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 3, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelCat1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelFechaFIN, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(LabelGameName, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(LabelGameName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCat, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelFechaINICIO, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCat1)
                    .addComponent(labelFechaFIN, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelCat2.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        labelCat2.setForeground(new java.awt.Color(255, 255, 255));
        labelCat2.setText("Fecha Inicio");

        labelCat3.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        labelCat3.setForeground(new java.awt.Color(255, 255, 255));
        labelCat3.setText("Fecha Fin");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCat3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCat2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addComponent(labelCat2)
                .addGap(18, 18, 18)
                .addComponent(labelCat3)
                .addGap(27, 27, 27))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelCat4.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        labelCat4.setForeground(new java.awt.Color(255, 255, 255));
        labelCat4.setText("Fecha Inicio");

        labelCat5.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        labelCat5.setForeground(new java.awt.Color(255, 255, 255));
        labelCat5.setText("Fecha Fin");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCat5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCat4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(156, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelGameName2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(LabelGameName2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(labelCat4)
                .addGap(18, 18, 18)
                .addComponent(labelCat5)
                .addGap(27, 27, 27))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelCat6.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        labelCat6.setForeground(new java.awt.Color(255, 255, 255));
        labelCat6.setText("Fecha Inicio");

        labelCat7.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        labelCat7.setForeground(new java.awt.Color(255, 255, 255));
        labelCat7.setText("Fecha Fin");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCat7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCat6, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addComponent(labelCat6)
                .addGap(18, 18, 18)
                .addComponent(labelCat7)
                .addGap(27, 27, 27))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelCat8.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        labelCat8.setForeground(new java.awt.Color(255, 255, 255));
        labelCat8.setText("Fecha Inicio");

        labelCat9.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        labelCat9.setForeground(new java.awt.Color(255, 255, 255));
        labelCat9.setText("Fecha Fin");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCat9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCat8, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addComponent(labelCat8)
                .addGap(18, 18, 18)
                .addComponent(labelCat9)
                .addGap(27, 27, 27))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelCat10.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        labelCat10.setForeground(new java.awt.Color(255, 255, 255));
        labelCat10.setText("Fecha Inicio");

        labelCat11.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        labelCat11.setForeground(new java.awt.Color(255, 255, 255));
        labelCat11.setText("Fecha Fin");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCat11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCat10, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addComponent(labelCat10)
                .addGap(18, 18, 18)
                .addComponent(labelCat11)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout PanelAlquileresLayout = new javax.swing.GroupLayout(PanelAlquileres);
        PanelAlquileres.setLayout(PanelAlquileresLayout);
        PanelAlquileresLayout.setHorizontalGroup(
            PanelAlquileresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAlquileresLayout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addGroup(PanelAlquileresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94)
                .addGroup(PanelAlquileresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(124, 124, 124))
        );
        PanelAlquileresLayout.setVerticalGroup(
            PanelAlquileresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAlquileresLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(PanelAlquileresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 41, Short.MAX_VALUE)
                .addGroup(PanelAlquileresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(PanelAlquileresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        PanelVentana.add(PanelAlquileres, "card6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(PanelVentana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelVentana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * event del botó Admin per obrir el frame de menu admin
     */
    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        // TODO add your handling code here:
        PanelVentana.removeAll();
        PanelVentana.add(PanelMenuAdmin);
        PanelVentana.repaint();
        PanelVentana.revalidate();
    }//GEN-LAST:event_btnAdminActionPerformed

    private void labelReseñasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_labelReseñasKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_labelReseñasKeyPressed

    private void panelAjustesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAjustesMouseClicked
        // TODO add your handling code here:
        PanelVentana.removeAll();
        PanelVentana.add(PanelAjustes);
        PanelVentana.repaint();
        PanelVentana.revalidate();
    }//GEN-LAST:event_panelAjustesMouseClicked

    private void panelVideojuegosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelVideojuegosMouseClicked
        // TODO add your handling code here:
        PanelVentana.removeAll();
        PanelVentana.add(PanelVideojuegos);
        PanelVentana.repaint();
        PanelVentana.revalidate();

        UpdateFilter();
        getPageNumber();
    }//GEN-LAST:event_panelVideojuegosMouseClicked

    private void labelVideojuegosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelVideojuegosMouseClicked

    }//GEN-LAST:event_labelVideojuegosMouseClicked

    private void txtNameEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameEditActionPerformed

    private void labelAjustesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAjustesMouseClicked
        // TODO add your handling code here:
        PanelVentana.removeAll();
        PanelVentana.add(PanelAjustes);
        PanelVentana.repaint();
        PanelVentana.revalidate();
    }//GEN-LAST:event_labelAjustesMouseClicked

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new login().setVisible(true);

    }//GEN-LAST:event_btnLogoutActionPerformed
    /**
     * event del botó del panel del menu admin que ens obrirà el frame de menu
     * de permisos d'usuari
     */
    private void btnPermisosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPermisosActionPerformed
        // TODO add your handling code here:
        new Permisos().setVisible(true);
    }//GEN-LAST:event_btnPermisosActionPerformed

    /**
     * event del botó del panel del menu admin que ens obrirà el frame d'alta de
     * videojocs
     */
    private void btnAltaVideojuegosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaVideojuegosActionPerformed
        // TODO add your handling code here:
        new AltaVideojuegos().setVisible(true);;
    }//GEN-LAST:event_btnAltaVideojuegosActionPerformed
    /**
     * event del botó del panel del menu admin que ens obrirà el frame d'edició
     * de videojocs
     */
    private void btnEditVideojuegosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditVideojuegosActionPerformed
        // TODO add your handling code here:
        new EditarVideojuegos().setVisible(true);
    }//GEN-LAST:event_btnEditVideojuegosActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        // TODO add your handling code here:
        new ControlUsuarios().setVisible(true);
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void labelTittleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelTittleMouseClicked
        // TODO add your handling code here:
        PanelVentana.removeAll();
        PanelVentana.add(PanelPrincipal);
        PanelVentana.repaint();
        PanelVentana.revalidate();
    }//GEN-LAST:event_labelTittleMouseClicked

    private void TotalGamesListAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TotalGamesListAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalGamesListAncestorAdded
    /**
     * event del botó del panel de editar dades d'usuari que ens guardara els
     * canvis fets
     */
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            // TODO add your handling code here:
            ClientConnection.getDos().writeByte(4);
            EditUser eu = new EditUser();

            eu.setUsername(ClientHelper.userName);
            if (!txtNameEdit.getText().trim().equals("")) {
                eu.setName(txtNameEdit.getText());
            }
            if (!txtMailEdit.getText().trim().equals("")) {
                eu.setMail(txtMailEdit.getText());
            }
            if (!txtPassEdit.getText().trim().equals("")) {
                eu.setPassword(Encrypter.getEncodedString(txtPassEdit.getText()));
            }
            ClientConnection.getOos().writeObject(eu);
            boolean correct = ClientConnection.getDis().readBoolean();

            if (correct) {
                if (!txtNameEdit.getText().trim().equals("")) {
                    user.setName(txtNameEdit.getText());
                }
                if (!txtMailEdit.getText().trim().equals("")) {
                    user.setMail(txtMailEdit.getText());
                }
                JOptionPane.showMessageDialog(this, "Se han guardado los cambios correctamente");
            }
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Error al guardar los cambios");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * acció del botó per anar a la primera pagina
     */
    private void btnFirstPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstPageActionPerformed
        // TODO add your handling code here:
        ActualPage = 1;
        UpdateFilter();
        getPageNumber();
    }//GEN-LAST:event_btnFirstPageActionPerformed

    private void btnLastPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastPageActionPerformed
        // TODO add your handling code here:
        ActualPage = totalPaginas;
        UpdateFilter();
        getPageNumber();
    }//GEN-LAST:event_btnLastPageActionPerformed
    /**
     * acció del botó per retrocedir de pagina
     */
    private void btnPageBeforeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPageBeforeActionPerformed
        // TODO add your handling code here:
        if (ActualPage > 1) {
            ActualPage--;
            UpdateFilter();
            getPageNumber();
        }
    }//GEN-LAST:event_btnPageBeforeActionPerformed

    /**
     * acció del botó per anar a la seguent pagina
     */
    private void btnNextPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextPageActionPerformed
        // TODO add your handling code here:
        if (ActualPage < totalPaginas) {
            ActualPage++;
            UpdateFilter();
            getPageNumber();
        }
    }//GEN-LAST:event_btnNextPageActionPerformed

    private void GamesListAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_GamesListAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_GamesListAncestorAdded

    private void btnDERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDERActionPerformed
        // TODO add your handling code here:
        if (contador == ClientHelper.listVideogamesTop5.size()) {
            contador = 0;
        }
        contador++;
        carruselLabel.setIcon(img[contador]);
    }//GEN-LAST:event_btnDERActionPerformed

    private void btnIZQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIZQActionPerformed
        // TODO add your handling code here:
        if (contador == 1) {
            contador = ClientHelper.listVideogamesTop5.size() + 1;
        }
        contador--;
        carruselLabel.setIcon(img[contador]);
    }//GEN-LAST:event_btnIZQActionPerformed

    private void btnAUTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAUTOActionPerformed
        // TODO add your handling code here:
        Timer timer = new Timer(600, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                carruselLabel.setIcon(new javax.swing.ImageIcon(img[contador].getImage()));
                contador++;
                if (contador == ClientHelper.listVideogamesTop5.size() + 1) {
                    contador = 1;
                }
            }
        });
        timer.start();
    }//GEN-LAST:event_btnAUTOActionPerformed

    private void TotalGamesListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TotalGamesListMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2 && !evt.isConsumed()) {
            evt.consume();
            System.out.println("entraaa");
            String name = TotalGamesList.getSelectedValue();
            Videogame[] videogame = new Videogame[1];
            ClientHelper.gameList.forEach(v -> {
                if (name.equals(v.getName())) {
                    videogame[0] = v;
                }
            });
            ClientHelper.videogameName = videogame[0].getName();
            new PantallaVideojuego(videogame[0]);
        }
    }//GEN-LAST:event_TotalGamesListMouseClicked

    private void btnSearchGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchGameActionPerformed
        // TODO add your handling code here:
        UpdateFilter();
    }//GEN-LAST:event_btnSearchGameActionPerformed

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        // TODO add your handling code here:
        UpdateFilter();
    }//GEN-LAST:event_btnFiltrarActionPerformed

    public void UpdateFilter() {

        if (ComboCategory.getSelectedItem() != null) {
            FiltroCat = (String) ComboCategory.getSelectedItem();
        } else {
            FiltroCat = null;
        }
        if (ComboPlatforms.getSelectedItem() != null) {
            FiltroPlat = (String) ComboPlatforms.getSelectedItem();
        } else {
            FiltroPlat = null;
        }
        if (txtScore.getText() != null && txtScore.getText().trim() != "") {
            FiltroScore = PantallaVideojuego.isScoreValid(txtScore.getText());
        } else {
            FiltroScore = -1;
        }
        if (txtReleaseDate.getText() != null && txtReleaseDate.getText().trim() != "") {
            FiltroDate = txtReleaseDate.getText();
        } else {
            FiltroDate = null;
        }
        if (txtSearch.getText() != null && txtSearch.getText().trim() != "") {
            FiltroName = txtSearch.getText();
        } else {
            FiltroName = null;
        }
        qfOld = qf;
        qf = new QueryFilter(FiltroPlat, FiltroCat, FiltroScore, FiltroDate, FiltroName);
        if (qfOld != qf) {
            ActualPage = 0;
        }
        getGamesLst(qf, ActualPage);
    }

    /**
     * metode que envia al servidor un byte perque ens torni un llistat dels
     * noms dels videojocs actuals de la base de dades amb la puntució més alta,
     * emplena el scrollPane
     */
    public void getTop5() throws IOException, ClassNotFoundException {

        DefaultListModel<String> model = new DefaultListModel<>();

        GamesList.setModel(model);

        String[] gameNames = ClientHelper.listVideogamesTop5.stream().map(v -> v.getName()).toArray(size -> new String[size]);

        for (int i = 0; i < gameNames.length; i++) {
            model.addElement(gameNames[i]);
        }
    }

    /**
     * metode que envia al servidor un byte perque ens torni un llistat dels
     * noms dels videojocs actuals de la base de dades Amb el llistat, emplena
     * el scrollPane
     */
    public void getGamesLst(QueryFilter qf, int paginaActual) {

        try {
            ClientConnection.getDos().writeByte(2);
            ClientConnection.getOos().writeObject(qf);
            totalPaginas = ClientConnection.getDis().readByte();
            ClientConnection.getDos().writeInt(paginaActual);
            ClientHelper.gameList = (List<Videogame>) ClientConnection.getOis().readObject();

            DefaultListModel<String> model = new DefaultListModel<>();

            TotalGamesList.setModel(model);

            String[] gameNames = ClientHelper.gameList.stream().map(v -> v.getName()).toArray(size -> new String[size]);

            for (int i = 0; i < gameNames.length; i++) {
                model.addElement(gameNames[i]);
            }

        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * metode per escriure al label el numero de pagina actual que es visualitza
     */
    public void getPageNumber() {

        labelNumPage.setText(ActualPage + "/" + totalPaginas);
    }
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboCategory;
    private javax.swing.JComboBox<String> ComboPlatforms;
    private javax.swing.JList<String> GamesList;
    private javax.swing.JLabel LabelGameName;
    private javax.swing.JLabel LabelGameName2;
    private javax.swing.JPanel PanelAjustes;
    private javax.swing.JPanel PanelAlquileres;
    private javax.swing.JPanel PanelMenuAdmin;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JPanel PanelVentana;
    private javax.swing.JPanel PanelVideojuegos;
    private javax.swing.JList<String> TotalGamesList;
    private javax.swing.JButton btnAUTO;
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnAltaVideojuegos;
    private javax.swing.JButton btnDER;
    private javax.swing.JButton btnEditVideojuegos;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnFirstPage;
    private javax.swing.JButton btnIZQ;
    private javax.swing.JButton btnLastPage;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnNextPage;
    private javax.swing.JButton btnPageBefore;
    private javax.swing.JButton btnPermisos;
    private javax.swing.JButton btnQuitarFiltros;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearchGame;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JLabel carruselLabel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel labelAjustes;
    private javax.swing.JLabel labelCat;
    private javax.swing.JLabel labelCat1;
    private javax.swing.JLabel labelCat10;
    private javax.swing.JLabel labelCat11;
    private javax.swing.JLabel labelCat2;
    private javax.swing.JLabel labelCat3;
    private javax.swing.JLabel labelCat4;
    private javax.swing.JLabel labelCat5;
    private javax.swing.JLabel labelCat6;
    private javax.swing.JLabel labelCat7;
    private javax.swing.JLabel labelCat8;
    private javax.swing.JLabel labelCat9;
    private javax.swing.JLabel labelCorreo;
    private javax.swing.JLabel labelFechaFIN;
    private javax.swing.JLabel labelFechaINICIO;
    private javax.swing.JLabel labelFiltros;
    private javax.swing.JLabel labelFondo;
    private javax.swing.JLabel labelFondoo;
    private javax.swing.JLabel labelFondoo1;
    private javax.swing.JLabel labelNombreApell;
    private javax.swing.JLabel labelNumPage;
    private javax.swing.JLabel labelPass;
    private javax.swing.JLabel labelPlatform1;
    private javax.swing.JLabel labelPlatform2;
    private javax.swing.JLabel labelPlatform3;
    private javax.swing.JLabel labelPlatform4;
    private javax.swing.JLabel labelReseñas;
    private javax.swing.JLabel labelTittle;
    private javax.swing.JLabel labelVideojuegos;
    private javax.swing.JLabel logoAjustes;
    private javax.swing.JLabel logoAlquiler;
    private javax.swing.JLabel logoJuegos;
    private javax.swing.JLabel logoReseñas;
    private javax.swing.JPanel panelAjustes;
    private javax.swing.JPanel panelAlquiler;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelReseñas;
    private javax.swing.JPanel panelTittle;
    private javax.swing.JPanel panelVideojuegos;
    private javax.swing.JTextField txtMailEdit;
    private javax.swing.JTextField txtNameEdit;
    private javax.swing.JTextField txtPassEdit;
    private javax.swing.JTextField txtReleaseDate;
    private javax.swing.JTextField txtScore;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

}
